import { Check, ChevronDown, CircleHelp, FolderPlus, GitBranch, Minus, Palette, PanelLeft, Plus, Search, Send, Settings, Sparkles, X } from 'lucide-react'
import { useEffect, useRef, useState, type CSSProperties } from 'react'

type Screen = 'loading' | 'theme' | 'connect' | 'settingUp' | 'start' | 'workspace'
type CursorTarget = { x: number; y: number }

const CURSOR: Record<Screen, CursorTarget> = { loading: { x: 50, y: 51 }, theme: { x: 31, y: 49 }, connect: { x: 47, y: 47 }, settingUp: { x: 47, y: 47 }, start: { x: 49, y: 43 }, workspace: { x: 69, y: 78 } }
const ZOOM_LEVELS = [0.85, 1, 1.15, 1.3]
const DESKTOP_WIDTH = 1280
const DESKTOP_HEIGHT = 720

/** Scripted, self-contained recreation of the desktop first-run path. */
export function GuiFirstRunTutorial() {
  const [screen, setScreen] = useState<Screen>('loading')
  const [cursor, setCursor] = useState<CursorTarget>(CURSOR.loading)
  const [click, setClick] = useState(0)
  const [playing, setPlaying] = useState(true)
  const [zoomIndex, setZoomIndex] = useState(1)
  const [reducedMotion, setReducedMotion] = useState(false)
  const viewportRef = useRef<HTMLDivElement>(null)
  const [fitScale, setFitScale] = useState(1)
  useEffect(() => {
    const viewport = viewportRef.current
    if (!viewport) return
    const updateFitScale = () => {
      const { width, height } = viewport.getBoundingClientRect()
      setFitScale(Math.min(width / DESKTOP_WIDTH, height / DESKTOP_HEIGHT))
    }
    updateFitScale()
    const observer = new ResizeObserver(updateFitScale)
    observer.observe(viewport)
    return () => observer.disconnect()
  }, [])
  useEffect(() => {
    const query = window.matchMedia('(prefers-reduced-motion: reduce)')
    const update = () => setReducedMotion(query.matches)
    update(); query.addEventListener('change', update)
    return () => query.removeEventListener('change', update)
  }, [])
  const move = (next: Screen, target = CURSOR[next], showClick = false) => { setCursor(target); if (showClick) setClick((value) => value + 1); setScreen(next) }
  useEffect(() => {
    if (!playing || reducedMotion) return
    const timers = [window.setTimeout(() => move('theme'), 750), window.setTimeout(() => move('theme', { x: 31, y: 49 }, true), 1450), window.setTimeout(() => move('connect', { x: 76, y: 86 }, true), 2150), window.setTimeout(() => move('settingUp', CURSOR.connect, true), 3050), window.setTimeout(() => move('start'), 4200), window.setTimeout(() => setPlaying(false), 4300)]
    return () => timers.forEach(window.clearTimeout)
  }, [playing, reducedMotion])
  const replay = () => { setPlaying(false); move('loading'); window.setTimeout(() => setPlaying(true), 0) }
  const chooseTheme = () => { setPlaying(false); move('theme', CURSOR.theme, true) }
  const next = () => { setPlaying(false); move('connect', { x: 76, y: 86 }, true) }
  const setupFree = () => { setPlaying(false); move('settingUp', CURSOR.connect, true); window.setTimeout(() => move('start'), reducedMotion ? 0 : 900) }
  const openWorkspace = () => { setPlaying(false); move('workspace', CURSOR.workspace, true) }
  const zoom = ZOOM_LEVELS[zoomIndex]
  return <section className="overflow-hidden rounded-lg border border-koma-border bg-koma-panel" aria-label="Desktop GUI first-run tutorial">
    <div className="flex flex-wrap items-center gap-3 border-b border-koma-border bg-koma-panel px-4 py-2.5"><span className="text-xs text-koma-dim">Scripted desktop emulation</span><span className="text-xs text-koma-fg">{screenLabel(screen)}</span><div className="ml-auto flex items-center gap-1.5"><div className="flex items-center rounded border border-koma-border bg-koma-panel2" aria-label="Stage zoom"><button type="button" onClick={() => setZoomIndex((value) => Math.max(0, value - 1))} disabled={zoomIndex === 0} aria-label="Zoom out" className="gui-tutorial-control"><Minus size={13} /></button><button type="button" onClick={() => setZoomIndex(1)} aria-label="Reset zoom" className="min-w-11 px-1 text-[11px] text-koma-dim hover:text-koma-fg">{Math.round(zoom * 100)}%</button><button type="button" onClick={() => setZoomIndex((value) => Math.min(ZOOM_LEVELS.length - 1, value + 1))} disabled={zoomIndex === ZOOM_LEVELS.length - 1} aria-label="Zoom in" className="gui-tutorial-control"><Plus size={13} /></button></div><button type="button" onClick={replay} className="rounded px-2 py-1 text-[11px] font-semibold text-koma-accent transition hover:bg-koma-hover">Replay</button></div></div>
    <div className="border-b border-koma-border bg-koma-panel2 px-5 py-4 text-sm leading-relaxed text-koma-fg">{narration(screen)}</div>
    <div className="gui-tutorial-viewport bg-koma-bg"><div ref={viewportRef} className="gui-tutorial-canvas"><div className="gui-tutorial-stage" style={{ '--gui-tutorial-scale': fitScale * zoom } as CSSProperties}><Desktop screen={screen} onTheme={chooseTheme} onNext={next} onFree={setupFree} onNewSession={openWorkspace} /><div aria-hidden="true" className="gui-tutorial-cursor pointer-events-none absolute z-30" style={{ transform: `translate(calc(${cursor.x}% - 12px), calc(${cursor.y}% - 12px))` }}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2"><path fill="currentColor" d="M4 2.5 19.2 12l-7.1 1.7L9 21.5 4 2.5Z" /><path d="m12 14 4.5 5" /></svg>{click > 0 && <span key={click} className="gui-tutorial-cursor-ring" />}</div></div></div></div>
    <div className="flex items-center justify-between bg-koma-panel px-4 py-2 text-[11px] text-koma-dim"><span>{reducedMotion ? 'Reduced motion: autoplay is paused and zoom changes instantly.' : 'Use zoom controls to inspect the complete desktop window.'}</span><span>Click the emulated controls to explore.</span></div>
  </section>
}

function Desktop({ screen, onTheme, onNext, onFree, onNewSession }: { screen: Screen; onTheme: () => void; onNext: () => void; onFree: () => void; onNewSession: () => void }) { const onboarding = screen === 'loading' || screen === 'theme' || screen === 'connect' || screen === 'settingUp'; return <div className="gui-desktop"><Titlebar /><div className="gui-desktop-body">{onboarding ? <OnboardingScreen screen={screen} onTheme={onTheme} onNext={onNext} onFree={onFree} /> : <AppShell workspace={screen === 'workspace'} onNewSession={onNewSession} />}</div></div> }
function Titlebar() { return <div className="gui-titlebar"><span className="font-semibold">koma</span><span className="ml-auto text-koma-fg opacity-35">Desktop</span><div className="ml-4 flex h-full"><button aria-label="Minimize"><Minus size={12} /></button><button aria-label="Maximize">□</button><button aria-label="Close" className="hover:bg-red-500/80"><X size={12} /></button></div></div> }
function OnboardingScreen({ screen, onTheme, onNext, onFree }: { screen: Screen; onTheme: () => void; onNext: () => void; onFree: () => void }) { if (screen === 'loading') return <div className="flex h-full flex-col items-center justify-center gap-3 text-koma-fg"><span className="text-xl font-bold">koma</span><span className="text-xs text-koma-dim"><span className="gui-tutorial-spinner">⠋</span> Loading configuration…</span></div>; const atConnect = screen === 'connect' || screen === 'settingUp'; return <div className="mx-auto flex h-full max-w-[560px] flex-col px-8 py-10"><div className="flex items-baseline gap-2"><span className="text-[24px] font-bold text-koma-fg">koma</span><span className="text-[12px] text-koma-fg opacity-45">first-run setup</span></div><div className="mb-6 mt-4 flex items-center gap-3 text-[11px]"><Step n="1" label="Theme" active={!atConnect} done={atConnect} /><span className="h-px w-5 bg-koma-border" /><Step n="2" label="Connect" active={atConnect} done={false} /><span className="h-px w-5 bg-koma-border" /><Step n="3" label="Model" active={false} done={false} /></div>{!atConnect ? <ThemeStep onTheme={onTheme} onNext={onNext} /> : <ConnectStep pending={screen === 'settingUp'} onFree={onFree} />}</div> }
function Step({ n, label, active, done }: { n: string; label: string; active: boolean; done: boolean }) { return <div className={`flex items-center gap-1.5 ${active ? 'text-koma-fg' : 'text-koma-fg opacity-45'}`}><span className={`flex h-5 w-5 items-center justify-center rounded-full border text-[10px] ${active ? 'border-koma-accent bg-koma-accent/15 text-koma-accent' : done ? 'border-koma-accent/50 text-koma-accent' : 'border-koma-border'}`}>{done ? <Check size={11} /> : n}</span>{label}</div> }
function ThemeStep({ onTheme, onNext }: { onTheme: () => void; onNext: () => void }) { return <div className="flex flex-1 flex-col"><p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-koma-fg opacity-45"><Palette className="mr-1 inline" size={12} />Pick a theme</p><p className="mb-3 text-[12px] text-koma-fg opacity-55">Selecting a theme repaints the app instantly. Default is dark — you can change this later.</p><div className="grid grid-cols-2 gap-2"><button onClick={onTheme} className="flex items-center justify-between rounded-lg border border-koma-accent bg-koma-accent/10 px-3 py-2.5 text-left text-[12.5px] text-koma-fg">Dark <Check size={14} className="text-koma-accent" /></button><div className="rounded-lg border border-koma-border px-3 py-2.5 text-[12.5px] text-koma-fg opacity-55">Github Dark</div></div><div className="mt-auto flex justify-end pt-6"><button onClick={onNext} className="rounded-lg border border-koma-border px-3.5 py-2 text-[12.5px] text-koma-fg hover:border-koma-accent/60 hover:bg-koma-hover">Next →</button></div></div> }
function ConnectStep({ pending, onFree }: { pending: boolean; onFree: () => void }) { return <div className="flex flex-1 flex-col"><p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-koma-fg opacity-45"><Sparkles className="mr-1 inline" size={12} />Connect a model</p><p className="mb-3 text-[12px] text-koma-fg opacity-55">Pick how koma should talk to a model. You can change this later.</p><button disabled={pending} onClick={onFree} className={`flex flex-col items-start gap-1 rounded-lg border px-3.5 py-3 text-left ${pending ? 'border-koma-border opacity-60' : 'border-koma-border hover:border-koma-accent/60 hover:bg-koma-hover'}`}><span className="flex items-center gap-1.5 text-[13px] font-semibold text-koma-fg"><Sparkles size={14} className="text-koma-accent" />Koma Free</span><span className="text-[11.5px] text-koma-fg opacity-60">{pending ? <><span className="gui-tutorial-spinner">⠋</span> Setting up…</> : 'Keyless, free tier — start chatting right away.'}</span></button><div className="mt-2 rounded-lg border border-koma-border px-3.5 py-3 text-[12px] text-koma-fg opacity-55">Provider <span className="block pt-1 text-[11px]">Bring your own API key.</span></div><div className="mt-2 rounded-lg border border-dashed border-koma-border px-3.5 py-3 text-[12px] text-koma-fg opacity-45">Sign in with OAuth <span className="block pt-1 text-[11px]">Connect from Connector after starting a session.</span></div></div> }
function AppShell({ workspace, onNewSession }: { workspace: boolean; onNewSession: () => void }) { return <div className="flex h-full"><nav className="gui-activity"><PanelLeft size={16} className="text-koma-accent" /><Search size={16} /><GitBranch size={16} /><span className="mt-auto" /><Settings size={16} /><CircleHelp size={16} /></nav><aside className="gui-sidebar"><div className="border-b border-koma-border px-4 py-3 text-[10px] uppercase tracking-wider text-koma-fg opacity-60">Explorer</div><div className="space-y-1 p-2 text-[11px] text-koma-fg opacity-60"><div className="rounded bg-koma-hover px-2 py-1.5 text-koma-fg">⌄ workspace</div><div className="px-2 py-1">▸ src</div><div className="px-2 py-1">▸ docs</div><div className="px-2 py-1">README.md</div></div></aside><main className="flex min-w-0 flex-1 flex-col">{workspace ? <Workspace /> : <StartScreen onNewSession={onNewSession} />}</main></div> }
function StartScreen({ onNewSession }: { onNewSession: () => void }) { return <><div className="flex h-[35px] items-center border-b border-koma-border px-4 text-[11px] text-koma-fg opacity-45">Welcome</div><div className="flex flex-1 items-center justify-center p-7"><div className="w-full max-w-[500px]"><div className="mb-5 flex items-baseline gap-2"><span className="text-[22px] font-bold text-koma-fg">koma</span><span className="text-[12px] text-koma-fg opacity-45">start a session</span></div><button onClick={onNewSession} className="flex w-full items-center gap-3 rounded-xl border border-koma-border bg-koma-panel px-4 py-3 text-left hover:border-koma-accent/60"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-koma-accent/15 text-koma-accent"><FolderPlus size={18} /></span><span><span className="block text-[13px] font-semibold text-koma-fg">New session</span><span className="text-[11px] text-koma-fg opacity-45">Start working in your default directory</span></span><span className="ml-auto text-koma-dim">→</span></button><div className="mt-4 rounded-xl border border-koma-border bg-koma-panel2 p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-koma-fg opacity-45">Recent</p><p className="mt-3 text-[12px] text-koma-fg opacity-35">No sessions yet — start a new one.</p></div></div></div><Status /></> }
function Workspace() { return <><div className="flex h-[35px] items-center gap-2 border-b border-koma-border px-4 text-[11px]"><span className="rounded bg-koma-hover px-2 py-1 text-koma-fg">New session</span><button className="ml-auto text-koma-dim"><ChevronDown size={14} /></button></div><div className="flex flex-1 flex-col overflow-hidden"><div className="flex-1 p-6"><div className="mb-5 text-[11px] text-koma-dim">Today</div><div className="max-w-[78%] rounded-lg bg-koma-panel px-3 py-2 text-[12px] text-koma-fg">Help me get started with this project.</div><div className="mt-4 max-w-[85%] text-[12px] leading-relaxed text-koma-fg">I&apos;m ready. Ask me to explore the workspace, make a change, or run a command.</div></div><div className="px-3 pb-3"><div className="rounded-2xl border border-koma-border bg-koma-panel px-3 py-2"><div className="h-7 text-[12px] text-koma-fg opacity-40">Message koma…</div><div className="flex items-center justify-between border-t border-koma-border pt-2 text-[10px] text-koma-dim"><span>◌ Koma Free · Auto</span><button aria-label="Send" className="flex h-7 w-7 items-center justify-center rounded-full bg-koma-accent text-koma-bg"><Send size={13} /></button></div></div></div></div><Status /></> }
function Status() { return <div className="flex h-6 items-center gap-4 border-t border-koma-border bg-koma-panel2 px-3 text-[9px] text-koma-dim"><span>main</span><span>UTF-8</span><span className="ml-auto">Koma Free</span></div> }
function screenLabel(screen: Screen) { return ({ loading: 'Starting', theme: 'Theme', connect: 'Connect', settingUp: 'Setting up', start: 'Start screen', workspace: 'Session workspace' })[screen] }
function narration(screen: Screen) { return ({ loading: 'The desktop frame stays present while the GUI waits for its initial configuration.', theme: 'First-run setup is a full-window onboarding screen; its title bar remains available while session chrome stays gated.', connect: 'Choose how to connect a model. Koma Free is the scripted keyless path; the other choices remain separate setup options.', settingUp: 'Koma Free remains pending until the host saves the provider and main model, then the onboarding gate unmounts.', start: 'A configured first run lands in the complete desktop shell and its start screen. Create a session to enter the chat workspace.', workspace: 'The opened session shows the full chat workspace, composer, navigation, and status footer.' })[screen] }
