import { ArrowLeft, ArrowRight, ArrowUp, Blocks, Bot, Brain, ChartColumn, Check, ChevronDown, ChevronRight, CircleHelp, Code2, Files, FolderPlus, GitBranch, Lock, Network, Paperclip, Plug, Search, Server, Settings, Sparkles, VectorSquare } from 'lucide-react'
import { type TutorialStage } from './model'

type Props = { stage: TutorialStage; onTheme: () => void; onNext: () => void; onFree: () => void; onSession: () => void }

/** Docs-local presentational copy of the production GUI shell; no production store, IPC, or components are imported. */
export function TutorialDesktop({ stage, ...actions }: Props) {
  const onboarding = stage === 'loading' || stage === 'theme' || stage === 'connect' || stage === 'settingUp'
  return <div className="gui-desktop">
    <Titlebar onboarding={onboarding} />
    <div className="gui-body">{onboarding ? <Onboarding stage={stage} {...actions} /> : <Shell attached={stage === 'session'} onSession={actions.onSession} />}</div>
  </div>
}

function Titlebar({ onboarding }: { onboarding: boolean }) {
  return <div className="gui-titlebar"><span id="gui-title">koma</span>{!onboarding && <button className="gui-command" aria-label="Change session"><Files size={13} /> <span>change session</span></button>}<div className="gui-window-controls"><button aria-label="Minimize">–</button><button aria-label="Maximize">☐</button><button aria-label="Close">✕</button></div></div>
}
function Step({ n, label, active, done }: { n: number; label: string; active: boolean; done: boolean }) { return <div className="gui-step"><span className={active ? 'active' : done ? 'done' : ''}>{done ? <Check size={12} /> : n}</span><label className={active ? 'current' : ''}>{label}</label></div> }
function Onboarding({ stage, onTheme, onNext, onFree }: Props) {
  if (stage === 'loading') return <div className="gui-onboard-loading"><b>koma</b><span>⠋ Loading configuration…</span></div>
  const connect = stage === 'connect' || stage === 'settingUp'
  return <div className="gui-onboarding"><div className="gui-onboard-brand"><b>koma</b><span>first-run setup</span></div><div className="gui-steps"><Step n={1} label="Theme" active={!connect} done={connect}/><i/><Step n={2} label="Connect" active={connect} done={false}/><i/><Step n={3} label="Model" active={false} done={false}/></div>{connect ? <Connect pending={stage === 'settingUp'} onFree={onFree} /> : <Theme onTheme={onTheme} onNext={onNext} />}</div>
}
function Theme({ onTheme, onNext }: Pick<Props, 'onTheme' | 'onNext'>) { return <div className="gui-onboard-content"><h3><Sparkles size={12}/> Pick a theme</h3><p>Selecting a theme repaints the app instantly. Default is dark — you can change this later.</p><div className="gui-theme-grid"><button className="selected" onClick={onTheme}>Dark <Check size={14}/></button><button>Github Dark <span/></button></div><div className="gui-onboard-next"><button onClick={onNext}>Next <ArrowRight size={15}/></button></div></div> }
function Connect({ pending, onFree }: { pending: boolean; onFree: () => void }) { return <div className="gui-onboard-content"><h3><Plug size={12}/> Connect a model</h3><p>Pick how koma should talk to a model. You can change this later.</p><div className="gui-connect-options"><button onClick={onFree} disabled={pending}><b><Sparkles size={14}/> Koma Free</b><span>{pending ? '⠋ Setting up…' : 'Keyless, free tier — start chatting right away.'}</span></button><button><b><Plug size={14}/> Provider</b><span>Bring your own API key (OpenRouter, OpenAI, DeepSeek, and more).</span></button><div><b><Lock size={14}/> Sign in with OAuth</b><span>Connect with your account — start a session first, then connect from Connector.</span></div></div><button className="gui-back"><ArrowLeft size={15}/> Theme</button></div> }

function Shell({ attached, onSession }: { attached: boolean; onSession: () => void }) { return <div className="gui-shell"><Activity /><Sidebar /><div className="gui-sidebar-resize" /><main className="gui-main">{attached ? <EmptySession /> : <Start onSession={onSession} />}</main></div> }
function Activity() { const items = [{ icon: Files, label: 'Explore' }, { icon: Code2, label: 'Coding' }, { icon: GitBranch, label: 'Source Control' }, { icon: VectorSquare, label: 'MCP' }, { icon: Brain, label: 'Connector' }, { icon: Network, label: 'Import Graph' }, { icon: Bot, label: 'Agents' }, { icon: ChartColumn, label: 'Usage' }, { icon: Blocks, label: 'Extensions' }, { icon: Server, label: 'Remote' }]; return <nav className="gui-activity" aria-label="Activity bar">{items.map(({ icon: Icon, label }, i) => <button key={label} className={i === 0 ? 'active' : ''} aria-label={label}><Icon size={20}/></button>)}<span/><button aria-label="Help"><CircleHelp size={20}/></button><button aria-label="Settings"><Settings size={20}/></button></nav> }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="gui-explorer-section"><h3><ChevronDown size={12}/>{title}</h3>{children}</section> }
function Empty({ children }: { children: React.ReactNode }) { return <div className="gui-empty">{children}</div> }
function Sidebar() { return <aside className="gui-sidebar"><header>Explorer</header><Section title="Plan"><Empty>No plan active</Empty></Section><Section title="File changed"><Empty>No changes</Empty></Section><Section title="Bash · 0"><Empty>No bash sessions</Empty></Section><Section title="Agents · 0"><Empty>No agents</Empty></Section></aside> }
function Start({ onSession }: { onSession: () => void }) { return <div className="gui-start"><div className="gui-start-columns"><div className="gui-start-actions"><div className="gui-start-heading"><b>koma</b><span>start a session</span></div><button className="gui-new-session" onClick={onSession}><i><FolderPlus size={18}/></i><span><b>New session</b><small>Start working in your default directory</small></span><ArrowRight size={16}/></button><div className="gui-recent"><label><span>◷</span> Recent</label><p>No sessions yet — start a new one.</p></div></div><div className="gui-about"><label>ⓘ About koma</label><p>A personal, terminal-first AI coding environment — agent + daemon at the core, driving your tools directly. This desktop shell renders your sessions natively while the daemon does the real work.</p><span>ϟ Multiple live sessions, resumable any time.</span><span>✦ Bring your own provider, or run the free keyless tier.</span></div></div></div> }
function EmptySession() { return <><div className="gui-chat"><div className="gui-chat-scroll" /></div><Composer /><Usage /></> }
function Composer() { return <div className="gui-composer"><div className="gui-compose-input">Message koma…</div><footer><div><button aria-label="Attach file"><Paperclip size={16}/></button><button aria-label="Search workspace files"><Search size={16}/></button><span>model</span><span>effort</span><span>auto</span></div><button className="gui-send" aria-label="Send" disabled><ArrowUp size={16}/></button></footer></div> }
function Usage() { return <footer className="gui-usage"><span>normal</span><i/><span>↑ 0 · cached 0 · ↓ 0 · <b>$0.0000</b></span><ChevronRight size={12}/></footer> }
