import { RST, ACC, FG, DIM, INVERSE, SEL_FG, SEL_BG, trunc, padRight, bar, chatHeader, chatInput } from './chat-chrome'
import type { TutorialStep } from './first-run-tutorial'

const W = 80
function commandEntry(rows: number): string { const lines = [...chatHeader(), '', '  With an active session, type /agents in the composer.', ...chatInput('/agents')]; while (lines.length < rows) lines.splice(2, 0, ''); return lines.slice(0, rows).map(l => trunc(l, W)).join('\n') }
const footer = (lines: string[], hint: string, rows: number) => { while (lines.length < rows - 1) lines.push(''); lines.push(INVERSE + padRight(' ' + hint, W) + RST); return lines.slice(0, rows).map(l => trunc(l, W)).join('\n') }
function header(lines: string[]) { lines.push(DIM + '  agents' + RST, DIM + bar('─', W) + RST) }
function pane(lines: string[], detail: string[]) {
  const left = ['› explore           built-in', '  reviewer          global', '  release-notes     session']
  for (let i = 0; i < Math.max(left.length, detail.length); i++) {
    const l = left[i] ?? ''; const styled = i === 0 ? SEL_FG + SEL_BG + padRight(l, 25) + RST : DIM + padRight(l, 25) + RST
    lines.push(styled + DIM + '│' + RST + '  ' + (detail[i] ?? ''))
  }
}
function browse(rows: number) { const lines: string[] = []; header(lines); pane(lines, [ACC + 'name          explore' + RST, DIM + 'source        built-in' + RST, DIM + 'description   Explore a codebase' + RST, DIM + 'model         (inherit main)' + RST, DIM + 'tools         read, grep, glob' + RST, '', DIM + 'prompt' + RST, FG + '  Find relevant files and explain their' + RST, FG + '  relationships before proposing changes.' + RST]); return footer(lines, '↑/↓ pick · →/Enter edit · n new · d delete · Esc close', rows) }
function edit(rows: number) { const lines: string[] = []; header(lines); pane(lines, [DIM + 'scope         session  (←/→ toggle)' + RST, ACC + '› name          api-review█' + RST, DIM + '  description   (required)' + RST, DIM + '  conditions    (optional — when to delegate)' + RST, DIM + '  model         (inherit main)  enter pick' + RST, DIM + '  tools         read, grep  enter pick' + RST, DIM + '  prompt' + RST, FG + '    Review API changes for correctness.' + RST]); return footer(lines, 'type to edit · Ctrl+J newline (prompt) · Enter/Esc done', rows) }
function picker(rows: number) { const lines: string[] = []; header(lines); pane(lines, [DIM + '› name          api-review' + RST, DIM + '  description   Review API changes' + RST, ACC + '  tools         read, grep  enter pick' + RST]); lines.push('', '', '                     ' + DIM + '┌─ ' + ACC + 'tools (2 selected)' + DIM + ' ───────────────────┐' + RST, '                     ' + DIM + '│' + RST + ' type to filter                       ' + DIM + '│' + RST, '                     ' + DIM + '│' + RST + SEL_FG + SEL_BG + '[x] read                              ' + RST + DIM + '│' + RST, '                     ' + DIM + '│' + RST + ACC + '[x] grep' + RST + '                              ' + DIM + '│' + RST, '                     ' + DIM + '│' + RST + ACC + '[ ] bash' + RST + '                              ' + DIM + '│' + RST, '                     ' + DIM + '│ space toggle                         │' + RST, '                     │ enter ok · esc cancel                │', '                     └──────────────────────────────────────┘'); return footer(lines, '↑/↓ field · Enter edit · s create · Esc cancel', rows) }
function prompt(rows: number) { const lines = [DIM + '  edit prompt' + RST, DIM + bar('─', W) + RST, '', DIM + '  1 ' + RST + FG + 'You are a focused subagent for API reviews.' + RST, DIM + '  2 ' + RST + FG + 'Check public interfaces, error handling, and tests.' + RST, DIM + '  3 ' + RST + FG + 'Report findings concisely.█' + RST]; return footer(lines, '↑↓←→ move · Enter newline · Ctrl+X clear · Esc save & back', rows) }
function deleting(rows: number) { const lines: string[] = []; header(lines); pane(lines, ['', FG + 'delete ' + RST + ACC + "'release-notes'" + RST + FG + '?' + RST, DIM + 'this removes the file from disk' + RST]); return footer(lines, 'y delete · n/Esc cancel', rows) }
export function getAgentsSteps(rows = 24): TutorialStep[] { return [
  { title: 'Enter /agents', narration: 'From an active chat session, type /agents in the composer and submit it. The command transitions from chat into the agents dashboard.', points: ['An active session is required.', 'The dashboard replaces the chat screen after the command is submitted.'], screen: commandEntry(rows) },
  { title: 'Browse agents', narration: 'The session-only /agents dashboard has a fixed 26-column sidebar and a detail pane.', points: ['A session is required before /agents can open.', 'The sidebar labels built-in, global, and session sources.', 'Enter moves from the list to edit the selected agent.'], screen: browse(rows) },
  { title: 'Create and select tools', narration: 'New agents choose session or global scope and edit their fields. Model and tool fields open dedicated pickers rather than accepting model text.', points: ['Name is inline editable; description, conditions, and prompt use the full-screen editor.', 'The tools picker is a checkbox multi-select with filtering.', 's creates or saves the draft.'], screen: picker(rows) },
  { title: 'Edit prompt fullscreen', narration: 'Prompt editing replaces the dashboard with a full-screen editor, line-number gutter, soft wrapping, and a cursor.', points: ['Enter inserts a newline.', 'Esc saves the field and returns to the agent form.', 'Ctrl+X asks before clearing the full field.'], screen: prompt(rows) },
  { title: 'Delete confirmation', narration: 'Deleting an agent requires an explicit confirmation.', points: ['Press y to delete.', 'Press n or Esc to cancel.'], screen: deleting(rows) },
] }
