import assert from 'node:assert/strict'
import { evalNumberExpr, isExprDraft, parseCompleteNumber } from './draftInput'

assert.equal(evalNumberExpr('20', 10), 20)
assert.equal(evalNumberExpr('100/2', 0), 50)
assert.equal(evalNumberExpr('12+4', 0), 16)
assert.equal(evalNumberExpr('3*4', 0), 12)
assert.equal(evalNumberExpr('(2+3)*4', 0), 20)
assert.equal(evalNumberExpr('2+3*4', 0), 14)
assert.equal(evalNumberExpr('+10', 5), 15)
assert.equal(evalNumberExpr('*2', 5), 10)
assert.equal(evalNumberExpr('/2', 10), 5)
assert.equal(evalNumberExpr('10%', 200), 20)
assert.equal(evalNumberExpr('1,5', 0), 1.5)
assert.equal(evalNumberExpr('12.', 0), 12)
assert.equal(evalNumberExpr('-3', 0), -3)
assert.equal(evalNumberExpr(' 100 / 2 ', 0), 50)
assert.equal(evalNumberExpr('', 5), null)
assert.equal(evalNumberExpr('12+', 5), null)
assert.equal(evalNumberExpr('abc', 5), null)
assert.equal(evalNumberExpr('100/0', 0), null)
assert.equal(evalNumberExpr('/0', 10), null)
assert.equal(parseCompleteNumber('8*3'), 24)
assert.equal(isExprDraft('100/2'), true)
assert.equal(isExprDraft('12+'), true)
assert.equal(isExprDraft(''), true)
assert.equal(isExprDraft('12px'), false)
assert.equal(isExprDraft('{radius}'), false)

console.log('draftInput ok')
