import { useEffect, useRef, useState } from 'react'
import { FlaskConical, Play, Square, Bug, RefreshCw, X, Terminal } from 'lucide-react'
import { useKoma } from '../store/koma'
import { codingRequest, workspaceKey, type WorkspaceRef, type CodingTaskRun } from '../lib/coding-service'
import { pathToUri } from '../lib/lsp-bridge'
import { breakpoints } from '../lib/coding-debug'
import { showCodingDebug } from './CodingDebug'
import { showCodingTasks } from './CodingTasks'
type Profile = { id: string; label: string; kind: string }
type Definitions = { profiles: Profile[]; fingerprint: string }
type Run = { id: string; profileId: string; label: string; mode: string; task: CodingTaskRun | null }
type Item = { id: string; label: string; file?: string; line?: number; suite?: string; status: string; durationMs?: number; message?: string }
type Results = { run: Run; items: Item[]; truncated: boolean }
const button = 'flex items-center gap-1 rounded px-1.5 py-1 text-koma-dim hover:bg-koma-hover hover:text-koma-fg disabled:opacity-40'
const active = (run?: Run) => !!run?.task && ['queued', 'running', 'stopping'].includes(run.task.status)
export function showCodingTests() { window.dispatchEvent(new Event('koma-coding-tests')) }
export function CodingTests() {
  const [open, setOpen] = useState(false), [workspace, setWorkspace] = useState<WorkspaceRef | null>(null), [known, setKnown] = useState<WorkspaceRef[]>([])
  const [definitions, setDefinitions] = useState<Definitions | null>(null), [profile, setProfile] = useState(''), [runs, setRuns] = useState<Run[]>([]), [runId, setRunId] = useState(''), [result, setResult] = useState<Results | null>(null)
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [refresh, setRefresh] = useState(0), [selected, setSelected] = useState<string[]>([]), [itemId, setItemId] = useState(''), [filter, setFilter] = useState(''), [group, setGroup] = useState('')
  const focus = useRef<HTMLElement | null>(null), closeRef = useRef<HTMLButtonElement>(null), epoch = useRef(0), mutation = useRef(false), pendingRun = useRef('')
  const scope = workspace ? workspaceKey(workspace) : ''; const run = runs.find(r => r.id === runId)
  useEffect(() => { const show = () => { const s = useKoma.getState(), hostId = s.remoteState.hostId ?? 'local', root = s.coding.activeRoot ?? s.settingsValues?.workdir?.[0]; focus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setKnown(old => [...new Map([...old, ...(s.settingsValues?.workdir ?? []).map(root => ({ hostId, root }))].map(w => [workspaceKey(w), w])).values()]); if (root) setWorkspace({ hostId, root }); setOpen(true); setRefresh(n => n + 1) }; window.addEventListener('koma-coding-tests', show); return () => window.removeEventListener('koma-coding-tests', show) }, [])
  useEffect(() => { if (open) closeRef.current?.focus() }, [open])
  useEffect(() => { epoch.current++; setRuns([]); setRunId(''); setResult(null); setError(''); setDefinitions(null); setSelected([]); setGroup('') }, [scope])
  useEffect(() => { if (!open || !workspace) return; const abort = new AbortController()
    void codingRequest<Definitions>(workspace, { op: 'testDefinitions' }, abort.signal).then(v => { if (!abort.signal.aborted) { setDefinitions(v); setProfile(p => v.profiles.some(x => x.id === p) ? p : v.profiles[0]?.id ?? '') } }).catch(e => { if (!abort.signal.aborted) setError(String(e)) })
    let timer: ReturnType<typeof setTimeout>; const poll = async () => { try { if (mutation.current) return; const v = await codingRequest<Run[]>(workspace, { op: 'testRuns' }, abort.signal); if (!abort.signal.aborted) { setRuns(v); const pending = pendingRun.current; pendingRun.current = ''; setRunId(id => v.some(r => r.id === pending) ? pending : v.some(r => r.id === id) ? id : v[v.length - 1]?.id ?? '') } } catch (e) { if (!abort.signal.aborted) setError(String(e)) } finally { if (!abort.signal.aborted) timer = setTimeout(poll, 1000) } }; void poll(); return () => { abort.abort(); clearTimeout(timer) }
  }, [open, scope, refresh])
  useEffect(() => { setResult(null); setSelected([]); setGroup(''); if (!open || !workspace || !runId) return; const abort = new AbortController(); let timer: ReturnType<typeof setTimeout>
    const poll = async () => { try { const v = await codingRequest<Results>(workspace, { op: 'testResults', runId }, abort.signal); if (!abort.signal.aborted) { setResult(v); setItemId(id => v.items.some(i => i.id === id) ? id : v.items[0]?.id ?? '') } } catch (e) { if (!abort.signal.aborted) setError(String(e)) } finally { if (!abort.signal.aborted) timer = setTimeout(poll, 750) } }; void poll(); return () => { abort.abort(); clearTimeout(timer) }
  }, [open, scope, runId])
  const close = () => { epoch.current++; setOpen(false); focus.current?.focus() }
  const act = async (mode: 'discover' | 'run' | 'failed' | 'stop' | 'debug', selection: string[] = []) => {
    if (!workspace || mutation.current || !definitions) return; mutation.current = true; setBusy(true); setError(''); const gen = epoch.current
    try { if (mode === 'debug') { await codingRequest(workspace, { op: 'testDebug', runId, itemId, breakpoints: breakpoints(workspace) }); if (gen === epoch.current) { close(); showCodingDebug(workspace) } }
      else if (mode === 'stop') await codingRequest(workspace, { op: 'testStop', runId })
      else { const value = await codingRequest<Run>(workspace, { op: 'testStart', profileId: profile, fingerprint: definitions.fingerprint, mode, previous: runId || undefined, selection }); if (gen === epoch.current) { pendingRun.current = value.id; setRuns(old => [...old, value]); setRunId(value.id) } }
      if (gen === epoch.current) setRefresh(n => n + 1)
    } catch (e) { if (gen === epoch.current) setError(String(e instanceof Error ? e.message : e)) } finally { mutation.current = false; setBusy(false) }
  }
  const reveal = (item: Item) => { if (!workspace || !item.file) return; if ((useKoma.getState().remoteState.hostId ?? 'local') !== workspace.hostId) { setError('Switch to this host to open test sources.'); return } useKoma.getState().openDiagnostic(pathToUri(workspace.root, item.file), Math.max(0, (item.line ?? 1) - 1), 0) }
  if (!open) return null
  const all = result?.items ?? [], groups = [...new Set(all.map(i => i.file ?? i.suite ?? 'Tests'))], items = all.filter(i => (!group || (i.file ?? i.suite ?? 'Tests') === group) && `${i.label} ${i.id}`.toLowerCase().includes(filter.toLowerCase())), item = all.find(i => i.id === itemId)
  const matching = run?.profileId === profile
  return <section role="region" aria-label="Test Explorer" className="absolute inset-x-10 bottom-6 z-40 flex h-[420px] max-h-[75vh] flex-col overflow-hidden rounded-md border border-koma-border bg-koma-panel text-[11px] text-koma-fg shadow-xl" onKeyDown={e => { if (e.key === 'Escape') { e.stopPropagation(); close() } }}>
    <div className="flex h-8 flex-none items-center gap-2 border-b border-koma-border px-2"><FlaskConical size={12} /><span className="text-koma-dim">TESTS</span><select aria-label="Test workspace" value={scope} disabled={busy} className="min-w-0 flex-1 bg-koma-panel" onChange={e => setWorkspace(known.find(w => workspaceKey(w) === e.target.value) ?? null)}>{known.map(w => <option key={workspaceKey(w)} value={workspaceKey(w)}>{w.hostId} · {w.root}</option>)}</select><button className={button} title="Refresh test profiles" onClick={() => setRefresh(n => n + 1)}><RefreshCw size={12} /></button><button ref={closeRef} className={button} aria-label="Close Test Explorer" onClick={close}><X size={12} /></button></div>
    <div className="flex flex-wrap items-center gap-1 border-b border-koma-border p-1"><select aria-label="Test runner" className="max-w-44 bg-koma-panel" value={profile} disabled={busy} onChange={e => setProfile(e.target.value)}>{definitions?.profiles.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select><button className={button} disabled={busy || !profile} onClick={() => void act('discover')}>Discover</button><button className={button} disabled={busy || !profile} onClick={() => void act('run')}><Play size={12} />Run all</button><button className={button} disabled={busy || !matching || !selected.length} onClick={() => void act('run', selected)}>Run selected ({selected.length})</button><button className={button} disabled={busy || !matching || !all.some(i => i.status === 'failed')} onClick={() => void act('failed')}>Rerun failed</button><button className={button} disabled={busy || !active(run)} title="Cancel test run" onClick={() => void act('stop')}><Square size={12} /></button><button className={button} disabled={busy || !matching || !item} title="Debug selected test" onClick={() => void act('debug')}><Bug size={12} /></button><button className={button} disabled={!workspace || !run?.task} title="Show test output" onClick={() => { if (workspace && run?.task) { close(); showCodingTasks('test', workspace, run.task.id) } }}><Terminal size={12} /></button></div>
    <div className="flex gap-2 items-center border-b border-koma-border p-1"><select aria-label="Test run" className="min-w-0 flex-1 bg-koma-panel" value={runId} onChange={e => setRunId(e.target.value)}>{runs.map(r => <option key={r.id} value={r.id}>{r.label} · {r.mode} · {r.task?.status ?? 'completed'}</option>)}</select><span className="text-koma-dim">{all.filter(i => i.status === 'passed').length} passed · {all.filter(i => i.status === 'failed').length} failed · {all.length} total</span><input aria-label="Filter tests" placeholder="Filter tests" value={filter} onChange={e => setFilter(e.target.value)} className="w-36 rounded border border-koma-border bg-koma-panel px-1" /></div>
    {(error || run?.task?.error) && <p role="alert" className="px-2 py-1 text-red-400">{error || run?.task?.error}</p>}{result?.truncated && <p className="px-2 text-koma-dim">Result limit reached; narrow the test selection. Retained output is available in Tasks.</p>}
    <div className="grid min-h-0 flex-1 grid-cols-[1fr_2fr_2fr] divide-x divide-koma-border">
      <div className="overflow-auto p-2"><button className={button} onClick={() => setGroup('')}>All files / suites</button>{groups.map(g => <div key={g} className="flex"><button className={`min-w-0 flex-1 truncate text-left py-1 ${group === g ? 'text-koma-fg' : 'text-koma-dim'}`} title={g} onClick={() => setGroup(g)}>{g}</button><button className={button} title="Run file or suite" disabled={busy || !matching} onClick={() => void act('run', all.filter(i => (i.file ?? i.suite ?? 'Tests') === g).map(i => i.id))}><Play size={10} /></button></div>)}</div>
      <div className="overflow-auto p-2">{!all.length && <p className="text-koma-dim">Discover tests to inspect them, or run the suite. Discovery can import or build project code.</p>}{items.map(i => <div key={i.id} className="flex items-start gap-1 py-0.5 hover:bg-koma-hover"><input aria-label={`Select ${i.label}`} type="checkbox" checked={selected.includes(i.id)} onChange={e => setSelected(old => e.target.checked ? [...old, i.id] : old.filter(id => id !== i.id))} /><button className="min-w-0 flex-1 text-left" onClick={() => setItemId(i.id)} onDoubleClick={() => reveal(i)}><span className={i.status === 'failed' ? 'text-red-400' : 'text-koma-fg'}>{i.label}</span><span className="ml-2 text-koma-dim">{i.status}{i.durationMs != null ? ` · ${Math.round(i.durationMs)} ms` : ''}</span></button></div>)}</div>
      <div className="overflow-auto p-2">{item && <><button className={`${button} break-all text-left`} disabled={!item.file} onClick={() => reveal(item)}>{item.file ?? item.suite ?? item.label}{item.line ? `:${item.line}` : ''}</button><pre className="whitespace-pre-wrap break-all text-koma-dim">{item.message || `${item.label}\n${item.status}`}</pre></>}</div>
    </div>
  </section>
}
