import { CodingDebugSource } from './CodingDebugSource'
import { showCodingTasks } from './CodingTasks'
import { useEffect, useRef, useState } from 'react'
import { Bug, Play, Square, StepForward, ArrowDownToLine, ArrowUpFromLine, Pause, RefreshCw, X, ChevronRight, ChevronDown, Terminal } from 'lucide-react'
import { useKoma, fileKey } from '../store/koma'
import { codingRequest, workspaceKey, type WorkspaceRef } from '../lib/coding-service'
import { breakpoints, setBreakpoints, updateRunningBreakpoints, setDebugExecution, readDebugWatches, saveDebugWatches, type DebugSession, type Breakpoint } from '../lib/coding-debug'
import { pathToUri } from '../lib/lsp-bridge'
const button = 'flex items-center gap-1 rounded px-1.5 py-1 text-koma-dim hover:bg-koma-hover hover:text-koma-fg disabled:opacity-40'
type Definitions = { profiles: { id: string; label: string; request: string }[]; fingerprint: string }
type Frame = { id: number; name: string; line: number; column: number; source?: { path?: string; name?: string; sourceReference?: number } }
type Variable = { name: string; value: string; type?: string; variablesReference: number }
type Request = <T>(command: string, args: Record<string, unknown>) => Promise<T>
function VariableRow({ variable, request, depth = 0 }: { variable: Variable; request: Request; depth?: number }) {
  const [children, setChildren] = useState<Variable[] | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const expand = async () => { setOpen(!open); if (!children && variable.variablesReference && depth < 12) { try { const result = await request<{ variables: Variable[] }>('variables', { variablesReference: variable.variablesReference }); setChildren(result.variables.slice(0, 500)) } catch (e) { setError(String(e)) } } }
  return <div><button className="flex max-w-full items-start gap-1 text-left hover:bg-koma-hover" onClick={() => void expand()} title={variable.type} disabled={!variable.variablesReference || depth >= 12}>{variable.variablesReference ? open ? <ChevronDown size={10} /> : <ChevronRight size={10} /> : <span className="w-2.5" />}<span className="text-koma-dim">{variable.name}</span><span className="break-all">{variable.value}</span></button>{open && <div className="ml-3">{error && <p className="text-koma-error">{error}</p>}{children?.map((v, i) => <VariableRow key={`${i}:${v.name}`} variable={v} request={request} depth={depth + 1} />)}</div>}</div>
}
export function showCodingDebug(workspace?: WorkspaceRef) { window.dispatchEvent(new CustomEvent('koma-coding-debug', { detail: { workspace } })) }
export function CodingDebug() {
  const [open, setOpen] = useState(false), [workspace, setWorkspace] = useState<WorkspaceRef | null>(null), [known, setKnown] = useState<WorkspaceRef[]>([])
  const [definitions, setDefinitions] = useState<Definitions | null>(null), [profile, setProfile] = useState(''), [sessions, setSessions] = useState<DebugSession[]>([]), [sessionId, setSessionId] = useState('')
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [refresh, setRefresh] = useState(0), [output, setOutput] = useState('')
  const [threads, setThreads] = useState<{ id: number; name: string }[]>([]), [threadId, setThreadId] = useState(0), [frames, setFrames] = useState<Frame[]>([]), [frameId, setFrameId] = useState(0), [scopes, setScopes] = useState<Variable[]>([])
  const [source, setSource] = useState<{ content: string; name: string; line: number } | null>(null)
  const [consoleInput, setConsoleInput] = useState('')
  const [watch, setWatch] = useState<string[]>([]), [expression, setExpression] = useState(''), [values, setValues] = useState<Variable[]>([]), [pointsVersion, setPointsVersion] = useState(0)
  const focus = useRef<HTMLElement | null>(null), closeRef = useRef<HTMLButtonElement>(null), epoch = useRef(0), mutation = useRef(false), pendingSession = useRef('')
  const scope = workspace ? workspaceKey(workspace) : ''; const session = sessions.find(s => s.id === sessionId); const paused = session?.status === 'stopped'; const generation = session?.generation
  useEffect(() => {
    const show = (event: Event) => { const target = (event as CustomEvent<{ workspace?: WorkspaceRef }>).detail?.workspace; const s = useKoma.getState(), hostId = s.remoteState.hostId ?? 'local', root = s.coding.activeRoot ?? s.settingsValues?.workdir?.[0]; focus.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setKnown(old => [...new Map([...old, ...(s.settingsValues?.workdir ?? []).map(root => ({ hostId, root }))].map(w => [workspaceKey(w), w])).values()]); if (target) { setWorkspace(target); setKnown(old => [...new Map([...old, target].map(w => [workspaceKey(w), w])).values()]) } else if (root) setWorkspace({ hostId, root }); setOpen(true); setRefresh(n => n + 1) }
    const points = (event: Event) => { const d = (event as CustomEvent<{ workspace: WorkspaceRef; path: string; points: Breakpoint[] }>).detail; setPointsVersion(n => n + 1); void updateRunningBreakpoints(d.workspace, d.path, d.points).catch(e => setError(String(e))) }
    window.addEventListener('koma-coding-debug', show); window.addEventListener('koma-breakpoints', points)
    return () => { window.removeEventListener('koma-coding-debug', show); window.removeEventListener('koma-breakpoints', points) }
  }, [])
  useEffect(() => { if (open) closeRef.current?.focus() }, [open])
  useEffect(() => { epoch.current++; setSource(null); setSessions([]); setSessionId(''); setError(''); setWatch(workspace ? readDebugWatches(workspace) : []); setValues([]); setDefinitions(null) }, [scope])
  useEffect(() => {
    if (!open || !workspace) return; const abort = new AbortController()
    void codingRequest<Definitions>(workspace, { op: 'debugDefinitions' }, abort.signal).then(v => { if (!abort.signal.aborted) { setDefinitions(v); setProfile(p => v.profiles.some(x => x.id === p) ? p : v.profiles[0]?.id ?? '') } }).catch(e => { if (!abort.signal.aborted) setError(String(e)) })
    let timer: ReturnType<typeof setTimeout>
    const poll = async () => { try { if (mutation.current) return; const value = await codingRequest<DebugSession[]>(workspace, { op: 'debugSessions' }, abort.signal); if (!abort.signal.aborted) { setSessions(value); const target = pendingSession.current; pendingSession.current = ''; setSessionId(id => value.some(s => s.id === target) ? target : value.some(s => s.id === id) ? id : value[value.length - 1]?.id ?? '') } } catch (e) { if (!abort.signal.aborted) setError(String(e)) } finally { if (!abort.signal.aborted) timer = setTimeout(poll, 500) } }; void poll()
    return () => { abort.abort(); clearTimeout(timer) }
  }, [open, scope, refresh])
  useEffect(() => { setOutput(''); if (!open || !workspace || !sessionId) return; const abort = new AbortController(); let after = 0; let timer: ReturnType<typeof setTimeout>
    const poll = async () => { try { const value = await codingRequest<{ events: { event: string; body: { output?: string } }[]; next: number; truncated: boolean }>(workspace, { op: 'debugEvents', sessionId, after }, abort.signal); if (abort.signal.aborted) return; after = value.next; const text = value.events.filter(e => e.event === 'output').map(e => e.body.output ?? '').join(''); if (text) setOutput(old => ((value.truncated ? '[Earlier output omitted]\n' : '') + old + text).slice(-262144)) } catch (e) { if (!abort.signal.aborted) setError(String(e)) } finally { if (!abort.signal.aborted) timer = setTimeout(poll, 600) } }; void poll(); return () => { abort.abort(); clearTimeout(timer) }
  }, [open, scope, sessionId])
  const request: Request = (command, args) => codingRequest(workspace!, { op: 'debugRequest', sessionId, command, arguments: args, generation })
  useEffect(() => {
    setThreads([]); setFrames([]); setScopes([]); setValues([]); if (!open || !paused) return; let canceled = false
    void request<{ threads: { id: number; name: string }[] }>('threads', {}).then(v => { if (!canceled) { setThreads(v.threads); setThreadId(id => v.threads.some(t => t.id === id) ? id : v.threads[0]?.id ?? 0) } }).catch(e => { if (!canceled) setError(String(e)) }); return () => { canceled = true }
  }, [open, scope, sessionId, paused, generation])
  useEffect(() => { setFrames([]); if (!open || !paused || !threadId) return; let canceled = false
    void request<{ stackFrames: Frame[] }>('stackTrace', { threadId, startFrame: 0, levels: 100 }).then(v => { if (!canceled) { setFrames(v.stackFrames); setFrameId(v.stackFrames[0]?.id ?? 0) } }).catch(e => { if (!canceled) setError(String(e)) }); return () => { canceled = true }
  }, [open, scope, sessionId, paused, generation, threadId])
  useEffect(() => { setScopes([]); if (!open || !paused || !frames.some(f => f.id === frameId)) return; let canceled = false
    void request<{ scopes: { name: string; variablesReference: number }[] }>('scopes', { frameId }).then(v => { if (!canceled) setScopes(v.scopes.map(s => ({ ...s, value: '' }))) }).catch(e => { if (!canceled) setError(String(e)) }); return () => { canceled = true }
  }, [open, scope, sessionId, paused, generation, frameId, frames])
  useEffect(() => { setValues([]); if (!open || !paused) return; let canceled = false
    void Promise.all(watch.map(async expression => { try { const v = await request<{ result: string; type?: string; variablesReference: number }>('evaluate', { expression, frameId, context: 'watch' }); return { name: expression, value: v.result, type: v.type, variablesReference: v.variablesReference } } catch (e) { return { name: expression, value: String(e), variablesReference: 0 } } })).then(v => { if (!canceled) setValues(v) }); return () => { canceled = true }
  }, [open, scope, sessionId, paused, generation, frameId, watch])
  useEffect(() => {
    if (!workspace) return
    const frame = frames.find(f => f.id === frameId)
    setDebugExecution(workspace, open && paused && frame?.source?.path ? { path: frame.source.path, line: Math.max(1, frame.line) } : null)
    return () => setDebugExecution(workspace, null)
  }, [open, scope, sessionId, generation, paused, frames, frameId])
  const changeWatches = (next: string[]) => { setWatch(next); if (workspace) saveDebugWatches(workspace, next) }
  const close = () => { epoch.current++; setOpen(false); focus.current?.focus() }
  const act = async (command: string, args?: Record<string, unknown>) => { if (!workspace || mutation.current) return; mutation.current = true; setBusy(true); setError(''); const gen = epoch.current
    try { if (command === 'start') { if (!definitions) return; const s = useKoma.getState(); const tab = s.ui.tabs.find(t => t.id === s.ui.activeTabId); const file = tab?.kind === 'codingFile' && tab.root === workspace.root && (s.remoteState.hostId ?? 'local') === workspace.hostId ? tab.path : undefined; if (file) { const f = s.coding.files[fileKey(workspace.root, file)]; if (f && f.content !== f.savedContent) throw new Error('Save the current file before debugging.') } const value = await codingRequest<DebugSession>(workspace, { op: 'debugStart', profileId: profile, fingerprint: definitions.fingerprint, file, breakpoints: breakpoints(workspace) }); if (gen === epoch.current) { pendingSession.current = value.id; setSessions(old => [...old, value]); setSessionId(value.id) } }
      else if (command === 'stop') await codingRequest(workspace, { op: 'debugStop', sessionId })
      else {
        const result = await request<{ result?: string }>(command, args ?? { threadId })
        if (command === 'evaluate' && gen === epoch.current) { setOutput(old => `${old}\n> ${String(args?.expression ?? '')}\n${result.result ?? ''}\n`.slice(-262144)); setConsoleInput('') }
      }
      if (gen === epoch.current) setRefresh(n => n + 1)
    } catch (e) { if (gen === epoch.current) setError(String(e instanceof Error ? e.message : e)) } finally { mutation.current = false; setBusy(false) }
  }
  const reveal = async (frame: Frame) => {
    if (!workspace || !frame.source) return
    const ticket = epoch.current
    if (frame.source.sourceReference) {
      try { const result = await request<{ content: string }>('source', { source: frame.source, sourceReference: frame.source.sourceReference }); if (result.content.length > 5 * 1024 * 1024) throw new Error('Debugger source exceeds 5 MiB'); if (ticket === epoch.current) setSource({ content: result.content, name: frame.source.name ?? frame.source.path ?? 'Debugger source', line: frame.line }) } catch (e) { if (ticket === epoch.current) setError(String(e)) }
    } else if (frame.source.path) {
      const s = useKoma.getState(); if ((s.remoteState.hostId ?? 'local') !== workspace.hostId) { setError('Switch to this host to open its source.'); return }
      s.openDiagnostic(pathToUri('', frame.source.path), frame.line - 1, frame.column - 1)
    }
  }
  const exceptionFilters = Array.isArray(session?.capabilities.exceptionBreakpointFilters) ? session.capabilities.exceptionBreakpointFilters as { filter: string; label: string; description?: string }[] : []
  const points = workspace ? Object.entries(breakpoints(workspace)) : []; void pointsVersion
  if (!open) return null
  return <section role="region" aria-label="Debugger" className="absolute inset-x-10 bottom-6 z-40 flex h-[420px] max-h-[75vh] flex-col overflow-hidden rounded-md border border-koma-border bg-koma-panel text-[11px] text-koma-fg shadow-xl" onKeyDown={e => { if (e.key === 'Escape') { e.stopPropagation(); close() } }}>
    {source && <CodingDebugSource source={source} close={() => setSource(null)} />}
    <div className="flex h-8 flex-none items-center gap-2 border-b border-koma-border px-2"><Bug size={12} /><span className="text-koma-dim">DEBUG</span><select aria-label="Debug workspace" value={scope} disabled={busy} className="min-w-0 flex-1 bg-koma-panel" onChange={e => setWorkspace(known.find(w => workspaceKey(w) === e.target.value) ?? null)}>{known.map(w => <option key={workspaceKey(w)} value={workspaceKey(w)}>{w.hostId} · {w.root}</option>)}</select><button className={button} title="Refresh debug profiles" onClick={() => setRefresh(n => n + 1)}><RefreshCw size={12} /></button><button ref={closeRef} className={button} aria-label="Close debugger" onClick={close}><X size={12} /></button></div>
    <div className="flex flex-wrap items-center gap-1 border-b border-koma-border p-1"><select aria-label="Launch configuration" className="max-w-52 bg-koma-panel" value={profile} onChange={e => setProfile(e.target.value)}>{definitions?.profiles.map(p => <option key={p.id} value={p.id}>{p.label}</option>)}</select><button className={button} disabled={busy || !profile} onClick={() => void act('start')} title="Start debugging"><Play size={12} /></button><select aria-label="Debug session" className="max-w-48 bg-koma-panel" value={sessionId} onChange={e => setSessionId(e.target.value)}>{sessions.map(s => <option key={s.id} value={s.id}>{s.label} · {s.status}</option>)}</select>{([{ id: 'continue', icon: Play, title: 'Continue', enabled: paused }, { id: 'pause', icon: Pause, title: 'Pause', enabled: session?.status === 'running' }, { id: 'next', icon: StepForward, title: 'Step over', enabled: paused }, { id: 'stepIn', icon: ArrowDownToLine, title: 'Step into', enabled: paused }, { id: 'stepOut', icon: ArrowUpFromLine, title: 'Step out', enabled: paused }, { id: 'stop', icon: Square, title: session?.request === 'attach' ? 'Detach' : 'Stop', enabled: session && ['starting', 'running', 'stopped'].includes(session.status) }]).map(a => <button key={a.id} className={button} disabled={busy || !a.enabled} title={a.title} onClick={() => void act(a.id)}><a.icon size={12} /></button>)}<button className={button} title="Open debug terminal" disabled={!session?.terminalTaskIds?.length && !session?.preLaunchTaskId} onClick={() => { const ids = [...(session?.preLaunchTaskId ? [session.preLaunchTaskId] : []), ...(session?.terminalTaskIds ?? [])]; if (workspace && ids.length) { close(); showCodingTasks(undefined, workspace, ids[ids.length - 1]) } }}><Terminal size={12} /></button><button className={button} onClick={() => { if (workspace && (useKoma.getState().remoteState.hostId ?? 'local') === workspace.hostId) void codingRequest(workspace, { op: 'configEnsure' }).then(() => { if ((useKoma.getState().remoteState.hostId ?? 'local') === workspace.hostId) useKoma.getState().openCodingFile(workspace.root, '.koma/coding.json') }).catch(e => setError(String(e))) }}>Configure</button></div>
    {(error || session?.error) && <p role="alert" className="flex-none px-2 py-1 text-koma-error">{error || session?.error}</p>}
    <div className="grid min-h-0 flex-1 grid-cols-3 divide-x divide-koma-border">
      <div className="overflow-auto p-2 space-y-2"><p className="text-koma-dim">CALL STACK</p><select aria-label="Debug thread" className="max-w-full bg-koma-panel" value={threadId} onChange={e => setThreadId(Number(e.target.value))}>{threads.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select>{frames.map(f => <button key={f.id} className={`block w-full truncate text-left hover:bg-koma-hover ${frameId === f.id ? 'text-koma-fg' : 'text-koma-dim'}`} onClick={() => { setFrameId(f.id); void reveal(f) }}>{f.name} · {f.line}</button>)}{exceptionFilters.length > 0 && <div className="space-y-1"><p className="text-koma-dim">EXCEPTIONS</p>{exceptionFilters.map(f => <label key={f.filter} title={f.description} className="flex items-center gap-1"><input type="checkbox" disabled={busy || !session || !['running', 'stopped'].includes(session.status)} checked={session?.exceptionFilters?.includes(f.filter) ?? false} onChange={e => void act('setExceptionBreakpoints', { filters: e.target.checked ? [...(session?.exceptionFilters ?? []), f.filter] : (session?.exceptionFilters ?? []).filter(id => id !== f.filter) })} />{f.label}</label>)}</div>}<p className="pt-2 text-koma-dim">BREAKPOINTS · F9 / gutter</p>{points.flatMap(([path, ps]) => ps.map(p => <div key={`${path}:${p.line}`} className="flex gap-1 items-center"><span className="truncate" title={path}>{path}:{p.line}</span><input aria-label={`Condition for ${path}:${p.line}`} placeholder="Condition" defaultValue={p.condition ?? ''} key={p.condition ?? ''} className="w-20 rounded border border-koma-border bg-koma-panel px-1" onBlur={e => { if (workspace && e.target.value !== (p.condition ?? '')) setBreakpoints(workspace, path, ps.map(b => b.line === p.line ? { ...b, condition: e.target.value || undefined } : b)) }} /><button className={button} title="Remove breakpoint" onClick={() => workspace && setBreakpoints(workspace, path, ps.filter(b => b.line !== p.line))}><X size={10} /></button></div>))}{Object.values(session?.breakpoints ?? {}).flatMap(v => v.breakpoints ?? []).filter(b => !b.verified).map((b, i) => <p key={i} className="text-koma-dim">Unverified: {b.message ?? `line ${b.line ?? '?'}`}</p>)}</div>
      <div className="overflow-auto p-2 space-y-2"><p className="text-koma-dim">VARIABLES</p>{scopes.map((v, i) => <VariableRow key={`${sessionId}:${generation}:${frameId}:${i}`} variable={v} request={request} />)}<p className="pt-2 text-koma-dim">WATCH</p><form className="flex gap-1" onSubmit={e => { e.preventDefault(); if (expression.trim() && watch.length < 32) { changeWatches([...watch, expression.trim().slice(0, 4096)]); setExpression('') } }}><input aria-label="Watch expression" value={expression} onChange={e => setExpression(e.target.value)} className="min-w-0 flex-1 rounded border border-koma-border bg-koma-panel px-1" /><button className={button}>+</button></form>{watch.map((name, i) => <div key={`${name}:${i}`} className="flex gap-1"><div className="min-w-0 flex-1"><VariableRow key={`${sessionId}:${generation}:${frameId}:${i}`} variable={values[i] ?? { name, value: paused ? '…' : 'Not paused', variablesReference: 0 }} request={request} /></div><button title="Remove watch" className={button} onClick={() => changeWatches(watch.filter((_, n) => n !== i))}><X size={10} /></button></div>)}</div>
      <div className="flex min-h-0 flex-col"><pre className="min-h-0 flex-1 overflow-auto whitespace-pre-wrap break-all p-2 text-koma-dim" aria-label="Debug console">{output || 'Debug output appears here.'}</pre><form className="flex gap-1 border-t border-koma-border p-1" onSubmit={e => { e.preventDefault(); if (consoleInput.trim()) void act('evaluate', { expression: consoleInput, frameId, context: 'repl' }) }}><input aria-label="Debug console expression" placeholder="Evaluate while paused" value={consoleInput} disabled={!paused || busy} onChange={e => setConsoleInput(e.target.value)} className="min-w-0 flex-1 bg-transparent px-1 outline-none" /><button className={button} disabled={!paused || busy || !consoleInput.trim()}><Play size={12} /></button></form></div>
    </div>
  </section>
}
