// Docs-local presentation transplant from src-webgui/src/components/{AccordionSection,ModelPicker}.tsx
// and src-webgui/src/components/panels/{helpers,form,connector/{ConnectorListView,ProviderForm,ModelForm}}.tsx.
// This module deliberately has no production store, daemon request, or animation imports.
import { useEffect, useState, type ReactNode } from 'react'
import { Bot, Check, ChevronDown, ChevronLeft, ChevronRight, Circle, CircleDot, Plus, Search, Server, Sparkles } from 'lucide-react'

export type Scope = 'global' | 'local'
export type Role = 'main' | 'awareness' | 'safeguard' | 'compactor' | 'planner'
export type Provider = { id: string; name: string; endpoint: string; hasKey: boolean }
export type Model = { id: string; name: string; modelId: string; provider: string; route: string; roles: Role[]; scope: Scope; sourceUuid?: string }
export type Route = { providerName: string; pricePrompt: string; priceCompletion: string; uptimeLast30m: number }
type View = 'list' | 'provider-picker' | 'provider-form' | 'model-form'

export const MODEL_IDS = ['gpt-4.1', 'gpt-4.1-mini', 'gpt-4o']
export const ROUTES: Route[] = [
  { providerName: 'OpenAI', pricePrompt: '2.00', priceCompletion: '8.00', uptimeLast30m: 100 },
  { providerName: 'Azure', pricePrompt: '2.20', priceCompletion: '8.80', uptimeLast30m: 99 },
]
const OPENAI: Provider = { id: 'provider-openai', name: 'OpenAI', endpoint: 'https://api.openai.com/v1', hasKey: true }
const MAIN_MODEL: Model = { id: 'model-gpt-4-1-main', name: 'GPT-4.1 main', modelId: 'gpt-4.1', provider: OPENAI.id, route: '', roles: ['main'], scope: 'global' }

export function useConnectorTutorial(step: number) {
  const [view, setView] = useState<View>('list')
  const [providers, setProviders] = useState<Provider[]>([])
  const [models, setModels] = useState<Model[]>([])
  const [sessionMain, setSessionMain] = useState<string | null>(null)
  const [armed, setArmed] = useState<string | null>(null)

  useEffect(() => {
    setArmed(null)
    setProviders(step >= 4 ? [OPENAI] : [])
    setModels(step >= 6 ? [MAIN_MODEL] : [])
    setSessionMain(step >= 7 ? MAIN_MODEL.id : null)
    setView(step === 2 ? 'provider-picker' : step === 3 ? 'provider-form' : step === 5 ? 'model-form' : 'list')
  }, [step])

  const saveProvider = (provider: Pick<Provider, 'name' | 'endpoint'>) => {
    setProviders([{ ...OPENAI, ...provider, hasKey: true }])
    setView('list')
  }
  const saveModel = (model: Model) => { setModels([model]); setView('list') }
  const removeProvider = (id: string) => { setProviders((items) => items.filter((item) => item.id !== id)); setArmed(null) }
  const removeModel = (id: string) => { setModels((items) => items.filter((item) => item.id !== id)); setArmed(null) }

  return { view, setView, providers, models, sessionMain, setSessionMain, armed, setArmed, saveProvider, saveModel, removeProvider, removeModel }
}

export function ConnectorPanel({ controller, target }: { controller: ReturnType<typeof useConnectorTutorial>; target?: string }) {
  const { view, setView, providers, models, armed, setArmed, saveProvider, saveModel, removeProvider, removeModel } = controller
  if (view === 'provider-picker' || view === 'provider-form') return <ProviderScreen form={view === 'provider-form'} onChoose={() => setView('provider-form')} onBack={() => setView('list')} onSave={saveProvider} target={target} />
  if (view === 'model-form') return <ModelScreen onBack={() => setView('list')} onSave={saveModel} target={target} />
  return <ConnectorListView providers={providers} models={models} armed={armed} onAddProvider={() => setView('provider-picker')} onAddModel={() => setView('model-form')} onArm={setArmed} onDisarm={() => setArmed(null)} onRemoveProvider={removeProvider} onRemoveModel={removeModel} target={target} />
}

function AccordionSection({ title, open, onToggle, action, children }: { title: string; open: boolean; onToggle: () => void; action?: ReactNode; children?: ReactNode }) {
  return <div className={`flex flex-col ${open ? 'min-h-0 flex-1' : 'flex-none'}`}><div className="group flex h-[22px] flex-none items-center bg-koma-head pr-1 hover:bg-koma-hover"><button type="button" onClick={onToggle} className="flex h-full flex-1 items-center gap-1 px-2 text-[11px] font-semibold uppercase tracking-wide text-koma-fg opacity-75 hover:opacity-100"><ChevronRight size={14} strokeWidth={2} className={`transition-transform ${open ? 'rotate-90' : ''}`} /><span className="truncate">{title}</span></button>{action && <div data-gui-tour-action className="flex items-center opacity-0 group-hover:opacity-100">{action}</div>}</div>{open && <div className="min-h-0 flex-1 overflow-y-auto pb-1">{children}</div>}</div>
}
function AddBtn({ label, onClick, target, tour }: { label: string; onClick: () => void; target?: boolean; tour?: string }) { return <button type="button" onClick={onClick} title={label} aria-label={label} data-gui-tour={tour} className={`flex h-5 w-5 items-center justify-center rounded text-koma-fg opacity-70 hover:bg-koma-hover hover:opacity-100 ${target ? 'gpm-target' : ''}`}><Plus size={14} /></button> }
function Empty({ children }: { children: ReactNode }) { return <div className="px-5 py-1.5 text-[12px] text-koma-fg opacity-35">{children}</div> }
function ScopePill({ scope }: { scope: Scope }) { return <span className={`flex-none rounded-full px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wide ${scope === 'global' ? 'bg-koma-accent/15 text-koma-accent' : 'bg-koma-fg/10 text-koma-fg opacity-60'}`}>{scope === 'global' ? 'glob' : 'local'}</span> }
function Row({ title, subtitle, leading, role, armed, onEdit, onArm, onDisarm, onConfirm }: { title: string; subtitle: string; leading?: ReactNode; role?: string; armed: boolean; onEdit: () => void; onArm: () => void; onDisarm: () => void; onConfirm: () => void }) {
  if (armed) return <div className="flex min-h-[42px] items-center gap-2 px-3 py-1.5"><span className="flex-1 truncate text-[12px] text-koma-fg">Remove “{title}”?</span><button type="button" onClick={onConfirm} aria-label="Confirm removal" className="text-emerald-500"><Check size={14}/></button><button type="button" onClick={onDisarm} aria-label="Cancel removal" className="text-koma-fg"><ChevronLeft size={14}/></button></div>
  return <div className="group flex min-h-[42px] items-center gap-2.5 px-3 py-1.5 hover:bg-koma-hover"><span className="flex-none">{leading}</span><button type="button" onClick={onEdit} className="min-w-0 flex-1 text-left"><span className="block truncate text-[13px] text-koma-fg">{title}</span><span className="block truncate text-[11px] text-koma-fg opacity-45">{subtitle}</span></button>{role && <span className="text-[10px] text-koma-fg opacity-55">{role}</span>}<button type="button" onClick={onArm} aria-label={`Delete ${title}`} className="opacity-0 group-hover:opacity-70">×</button></div>
}
function ConnectorListView({ providers, models, armed, onAddProvider, onAddModel, onArm, onDisarm, onRemoveProvider, onRemoveModel, target }: { providers: Provider[]; models: Model[]; armed: string | null; onAddProvider: () => void; onAddModel: () => void; onArm: (id: string) => void; onDisarm: () => void; onRemoveProvider: (id: string) => void; onRemoveModel: (id: string) => void; target?: string }) {
  const [open, setOpen] = useState({ providers: true, oauth: true, models: true })
  return <div className="absolute inset-0 flex min-h-0 flex-col overflow-hidden bg-koma-panel"><AccordionSection title="Providers" open={open.providers} onToggle={() => setOpen((s) => ({ ...s, providers: !s.providers }))} action={<AddBtn label="Add provider" onClick={onAddProvider} target={target === 'add-provider'} tour="add-provider" />}>{providers.length ? providers.map((provider) => <Row key={provider.id} title={provider.name} subtitle={provider.endpoint} role="••••" armed={armed === provider.id} onEdit={onAddProvider} onArm={() => onArm(provider.id)} onDisarm={onDisarm} onConfirm={() => onRemoveProvider(provider.id)} />) : <Empty>No providers</Empty>}</AccordionSection><AccordionSection title="OAuth" open={open.oauth} onToggle={() => setOpen((s) => ({ ...s, oauth: !s.oauth }))} action={<AddBtn label="Connect account" onClick={() => undefined} /> }><Empty>No connections</Empty></AccordionSection><AccordionSection title="Models" open={open.models} onToggle={() => setOpen((s) => ({ ...s, models: !s.models }))} action={<AddBtn label="Add model" onClick={onAddModel} target={target === 'add-model'} tour="add-model" />}>{models.length ? models.map((model) => <Row key={model.id} leading={<ScopePill scope={model.scope}/>} title={model.name} subtitle={`${model.modelId} · OpenAI`} role={model.roles[0]} armed={armed === model.id} onEdit={onAddModel} onArm={() => onArm(model.id)} onDisarm={onDisarm} onConfirm={() => onRemoveModel(model.id)} />) : <Empty>No models</Empty>}</AccordionSection></div>
}

function DetailHeader({ title, onBack }: { title: string; onBack: () => void }) { return <div className="flex h-8 flex-none items-center gap-1 border-b border-koma-border px-2"><button type="button" onClick={onBack} aria-label="Back" className="flex h-6 w-6 items-center justify-center rounded text-koma-fg opacity-70 hover:bg-koma-hover"><ChevronLeft size={16}/></button><span className="text-[12px] font-semibold text-koma-fg">{title}</span></div> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <div className="flex flex-col gap-1 px-3 py-1.5"><span className="text-[10px] font-semibold uppercase tracking-wider text-koma-fg opacity-50">{label}</span>{children}</div> }
const inputClass = 'h-7 w-full rounded border border-koma-border bg-koma-bg px-2 text-[12px] text-koma-fg outline-none placeholder:text-koma-fg placeholder:opacity-35 focus:border-koma-grip'
function Actions({ onCancel, onSave, saveDisabled, target, tour }: { onCancel: () => void; onSave: () => void; saveDisabled?: boolean; target?: boolean; tour?: string }) { return <div className="flex flex-none items-center justify-end gap-2 border-t border-koma-border px-3 py-2"><button type="button" onClick={onCancel} className="rounded px-2.5 py-1 text-[12px] text-koma-fg opacity-70 hover:bg-koma-hover">Cancel</button><button type="button" onClick={onSave} disabled={saveDisabled} data-gui-tour={tour} className={`rounded border border-koma-border px-2.5 py-1 text-[12px] text-koma-fg enabled:hover:bg-koma-hover disabled:opacity-40 ${target ? 'gpm-target' : ''}`}>Save</button></div> }
function ProviderScreen({ form, onChoose, onBack, onSave, target }: { form: boolean; onChoose: () => void; onBack: () => void; onSave: (provider: Pick<Provider, 'name' | 'endpoint'>) => void; target?: string }) {
  const [name, setName] = useState('OpenAI'); const [endpoint, setEndpoint] = useState('https://api.openai.com/v1')
  return <div className="absolute inset-0 flex flex-col bg-koma-panel"><DetailHeader title="Add provider" onBack={onBack}/>{!form ? <div className="flex-1 overflow-auto py-1"><div className="px-3 pb-1 pt-2 text-[10px] font-semibold uppercase tracking-wider text-koma-fg opacity-50">Choose a provider</div><div className="flex flex-col gap-0.5 px-2"><button type="button" data-gui-tour="openai" onClick={onChoose} className={`flex items-center gap-2 rounded px-2 py-1.5 text-left hover:bg-koma-hover ${target === 'openai' ? 'gpm-target' : ''}`}><Server size={14} className="flex-none text-koma-accent"/><span className="flex min-w-0 flex-1 flex-col"><span className="text-[12.5px] text-koma-fg">OpenAI</span><span className="truncate text-[10.5px] text-koma-fg opacity-40">https://api.openai.com/v1</span></span><ChevronRight size={13} className="text-koma-fg opacity-30"/></button><button type="button" className="flex items-center gap-2 rounded px-2 py-1.5 text-left hover:bg-koma-hover"><Server size={14} className="text-koma-accent"/><span className="text-[12.5px] text-koma-fg">OpenRouter</span></button></div></div> : <><div className="flex-1 overflow-auto py-1"><Field label="Name"><input className={inputClass} value={name} onChange={(e) => setName(e.target.value)}/></Field><Field label="Endpoint (base URL)"><input className={inputClass} value={endpoint} onChange={(e) => setEndpoint(e.target.value)}/></Field><Field label="API key"><input className={inputClass} type="password" placeholder="Illustrative value only — never saved" aria-describedby="tutorial-key-note"/></Field><p id="tutorial-key-note" className="px-3 text-[10px] text-koma-fg opacity-45">This local example accepts no credential value and makes no request.</p></div><Actions onCancel={onBack} onSave={() => onSave({ name, endpoint })} saveDisabled={!name.trim()} target={target === 'save-provider'} tour="save-provider"/></>}</div>
}
function ModelScreen({ onBack, onSave, target }: { onBack: () => void; onSave: (model: Model) => void; target?: string }) {
  const [model, setModel] = useState(MAIN_MODEL); const patch = (partial: Partial<Model>) => setModel((value) => ({ ...value, ...partial })); const toggle = (role: Role) => patch({ roles: model.roles.includes(role) ? model.roles.filter((value) => value !== role) : [...model.roles, role] })
  return <div className="absolute inset-0 flex flex-col bg-koma-panel"><DetailHeader title="Add model" onBack={onBack}/><div className="flex-1 overflow-auto py-1"><Field label="Name"><input className={inputClass} value={model.name} onChange={(e) => patch({ name: e.target.value })}/></Field><Field label="Provider"><select className={inputClass} value={model.provider} onChange={(e) => patch({ provider: e.target.value })}><option value={OPENAI.id}>OpenAI</option></select></Field><Field label="Model id"><input className={inputClass} list="tutorial-model-ids" value={model.modelId} onChange={(e) => patch({ modelId: e.target.value })}/><datalist id="tutorial-model-ids">{MODEL_IDS.map((id) => <option key={id} value={id}/>)}</datalist></Field><Field label="Route"><div role="radiogroup" className="flex flex-col gap-0.5 rounded border border-koma-border p-1"><RouteRow label="Auto" selected={!model.route} onClick={() => patch({ route: '' })}/>{ROUTES.map((route) => <RouteRow key={route.providerName} label={`${route.providerName}  $${route.pricePrompt}/$${route.priceCompletion}  ${route.uptimeLast30m}%`} selected={model.route === route.providerName} onClick={() => patch({ route: route.providerName })}/>)}</div></Field><Field label="Roles"><div className="flex flex-wrap gap-1">{(['main', 'awareness', 'safeguard', 'compactor', 'planner'] as Role[]).map((role) => <button key={role} type="button" aria-pressed={model.roles.includes(role)} onClick={() => toggle(role)} className={`flex items-center gap-1 rounded border px-2 py-0.5 text-[11px] ${model.roles.includes(role) ? 'border-koma-accent bg-koma-accent/15 text-koma-fg' : 'border-koma-border text-koma-fg opacity-45'}`}>{model.roles.includes(role) && <Check size={11} className="text-koma-accent"/>}{role}</button>)}</div></Field><Field label="Scope"><select className={inputClass} value={model.scope} onChange={(e) => patch({ scope: e.target.value as Scope })}><option value="global">Global</option><option value="local">Local</option></select></Field></div><Actions onCancel={onBack} onSave={() => onSave(model)} saveDisabled={!model.name.trim()} target={target === 'save-model'} tour="save-model"/></div>
}
function RouteRow({ label, selected, onClick }: { label: string; selected: boolean; onClick: () => void }) { return <button type="button" role="radio" aria-checked={selected} onClick={onClick} className={`flex w-full items-center gap-2 overflow-hidden rounded px-2 py-1 text-left text-[12px] ${selected ? 'bg-koma-accent/15 text-koma-fg' : 'text-koma-fg opacity-75 hover:bg-koma-hover'}`}>{selected ? <CircleDot size={13} className="text-koma-accent"/> : <Circle size={13} className="opacity-40"/>}<span>{label}</span></button> }

export function ModelPicker({ models, sessionMain, onSelect, target }: { models: Model[]; sessionMain: string | null; onSelect: (id: string | null) => void; target?: boolean }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const globals = models.filter((model) => model.scope === 'global'); const filtered = globals.filter((model) => `${model.name} ${model.modelId} OpenAI`.toLowerCase().includes(query.toLowerCase())); const current = globals.find((model) => model.id === sessionMain)
  return <div className="relative"><button type="button" data-gui-tour={target ? 'model-picker' : undefined} onClick={() => setOpen((value) => !value)} className={`flex h-8 max-w-[160px] items-center gap-1 rounded-lg px-2 text-[12px] text-koma-fg opacity-70 hover:bg-koma-hover ${target ? 'gpm-target' : ''}`}><Bot size={15}/><span className="truncate">{current?.name ?? '(inherit)'}</span><ChevronDown size={12}/></button>{open && <div className="absolute bottom-[calc(100%+6px)] left-0 z-30 w-[260px] overflow-hidden rounded-md border border-koma-border bg-koma-panel shadow-sm"><div className="flex h-[26px] items-center gap-2 border-b border-koma-border px-2"><Search size={12} className="opacity-50"/><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search models…" className="w-full bg-transparent text-[12px] text-koma-fg outline-none"/></div><div className="max-h-[240px] overflow-y-auto py-1"><PickerRow label="(inherit) — global main" active={!sessionMain} onClick={() => { onSelect(null); setOpen(false) }}/>{filtered.map((model) => <PickerRow key={model.id} label={model.name} subtitle={`${model.modelId} · OpenAI`} active={sessionMain === model.id} onClick={() => { onSelect(model.id); setOpen(false) }}/>)}</div></div>}</div>
}
function PickerRow({ label, subtitle, active, onClick }: { label: string; subtitle?: string; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`flex w-full items-center gap-2 px-2 py-1.5 text-left text-[12px] ${active ? 'bg-koma-hover text-koma-fg' : 'text-koma-fg opacity-75 hover:bg-koma-hover'}`}>{active ? <Check size={12} className="text-koma-accent"/> : <span className="w-3"/>}<span><span className="block">{label}</span>{subtitle && <span className="block text-[10px] opacity-50">{subtitle}</span>}</span>{label.includes('free') && <Sparkles size={9}/>}</button> }
