//! [`Role`] enum and the two sentinel constants used across the message layer.

use serde::{Deserialize, Serialize};

/// Prefix marking a tool result as a harness-internal message (e.g. the silent
/// "plan first" nudge) that should be fed to the model but NOT shown in the
/// transcript. An invisible char so it never affects what the model reads.
pub const PLAN_NUDGE_MARK: &str = "\u{2063}";

/// Marks the boundary in a System message between the STABLE cached head and
/// the volatile (per-session-changing) tail (project file listing, awareness
/// summary). `to_wire` puts the cache breakpoint on the head only.
pub const CACHE_SPLIT_MARK: &str = "\u{2062}\u{2061}";

/// Prefix marking a `User` message as the output of the `!` user-shell shortcut
/// (a command the user ran directly in the session cwd, NOT a message to the
/// model). The transcript renders such a message distinctly (a `$ <cmd>` header
/// over dim output) instead of the normal `★` user bullet, and the wire builder
/// (`to_wire`) STRIPS this invisible char so the model still sees the clean
/// `$ <cmd>\n<output>` text as context. An invisible char so, even on the off
/// chance it reaches the model un-stripped, it never affects what the model reads.
pub const SHELL_MARK: &str = "\u{2064}";

/// Which participant authored a message.
///
/// Serialised as lowercase strings (`"system"`, `"user"`, `"assistant"`) to
/// match the OpenRouter / OpenAI chat-completions wire format.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    /// The hidden prompt that sets the assistant's behaviour. Always the first
    /// message in a conversation; rebuilt from embedded resources + MEMORY.md
    /// on every session load via `Session::rebuild_system`.
    System,
    /// A message typed by the human in the TUI.
    User,
    /// A response generated by the model (streamed or non-streamed).
    Assistant,
    /// The result of running a tool, fed back to the model. Carries a
    /// `tool_call_id` pointing at the assistant `tool_calls` entry it answers.
    Tool,
}

impl Role {
    /// Short display label used in the TUI chat view.
    #[allow(dead_code)]
    pub fn as_str(&self) -> &'static str {
        match self {
            Role::System => "sys",
            Role::User => "you",
            Role::Assistant => "ai",
            Role::Tool => "tool",
        }
    }
}
