/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as DocsDocsRouteImport } from './routes/_docs/docs'
import { Route as DocsDocsArchitectureRouteImport } from './routes/_docs/docs/architecture'
import { Route as DocsDocsCommandsAdddirRouteImport } from './routes/_docs/docs/commands-adddir'
import { Route as DocsDocsCommandsAgentsRouteImport } from './routes/_docs/docs/commands-agents'
import { Route as DocsDocsCommandsAllRouteImport } from './routes/_docs/docs/commands-all'
import { Route as DocsDocsCommandsAttachRouteImport } from './routes/_docs/docs/commands-attach'
import { Route as DocsDocsCommandsBashRouteImport } from './routes/_docs/docs/commands-bash'
import { Route as DocsDocsCommandsCdRouteImport } from './routes/_docs/docs/commands-cd'
import { Route as DocsDocsCommandsClearRouteImport } from './routes/_docs/docs/commands-clear'
import { Route as DocsDocsCommandsCompactRouteImport } from './routes/_docs/docs/commands-compact'
import { Route as DocsDocsCommandsEffortRouteImport } from './routes/_docs/docs/commands-effort'
import { Route as DocsDocsCommandsExtensionRouteImport } from './routes/_docs/docs/commands-extension'
import { Route as DocsDocsCommandsFreeRouteImport } from './routes/_docs/docs/commands-free'
import { Route as DocsDocsCommandsHelpRouteImport } from './routes/_docs/docs/commands-help'
import { Route as DocsDocsCommandsInternetRouteImport } from './routes/_docs/docs/commands-internet'
import { Route as DocsDocsCommandsMcpRouteImport } from './routes/_docs/docs/commands-mcp'
import { Route as DocsDocsCommandsModeRouteImport } from './routes/_docs/docs/commands-mode'
import { Route as DocsDocsCommandsModelRouteImport } from './routes/_docs/docs/commands-model'
import { Route as DocsDocsCommandsNewRouteImport } from './routes/_docs/docs/commands-new'
import { Route as DocsDocsCommandsQuitRouteImport } from './routes/_docs/docs/commands-quit'
import { Route as DocsDocsCommandsRemoteRouteImport } from './routes/_docs/docs/commands-remote'
import { Route as DocsDocsCommandsRenameRouteImport } from './routes/_docs/docs/commands-rename'
import { Route as DocsDocsCommandsResumeRouteImport } from './routes/_docs/docs/commands-resume'
import { Route as DocsDocsCommandsSecurityRouteImport } from './routes/_docs/docs/commands-security'
import { Route as DocsDocsCommandsSelectRouteImport } from './routes/_docs/docs/commands-select'
import { Route as DocsDocsCommandsSkillRouteImport } from './routes/_docs/docs/commands-skill'
import { Route as DocsDocsCommandsStoreRouteImport } from './routes/_docs/docs/commands-store'
import { Route as DocsDocsCommandsTaskRouteImport } from './routes/_docs/docs/commands-task'
import { Route as DocsDocsCommandsTodoRouteImport } from './routes/_docs/docs/commands-todo'
import { Route as DocsDocsCommandsUsageRouteImport } from './routes/_docs/docs/commands-usage'
import { Route as DocsDocsGettingStartedRouteImport } from './routes/_docs/docs/getting-started'
import { Route as DocsDocsGuiRouteImport } from './routes/_docs/docs/gui'
import { Route as DocsDocsKeyboardShortcutsRouteImport } from './routes/_docs/docs/keyboard-shortcuts'
import { Route as DocsDocsOverviewRouteImport } from './routes/_docs/docs/overview'
import { Route as DocsDocsSettingsModelRouteImport } from './routes/_docs/docs/settings-model'
import { Route as DocsDocsSettingsOauthRouteImport } from './routes/_docs/docs/settings-oauth'
import { Route as DocsDocsSettingsProviderRouteImport } from './routes/_docs/docs/settings-provider'
import { Route as DocsDocsTuiRouteImport } from './routes/_docs/docs/tui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsRoute = DocsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocsArchitectureRoute = DocsDocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsAdddirRoute = DocsDocsCommandsAdddirRouteImport.update({
  id: '/commands-adddir',
  path: '/commands-adddir',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsAgentsRoute = DocsDocsCommandsAgentsRouteImport.update({
  id: '/commands-agents',
  path: '/commands-agents',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsAllRoute = DocsDocsCommandsAllRouteImport.update({
  id: '/commands-all',
  path: '/commands-all',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsAttachRoute = DocsDocsCommandsAttachRouteImport.update({
  id: '/commands-attach',
  path: '/commands-attach',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsBashRoute = DocsDocsCommandsBashRouteImport.update({
  id: '/commands-bash',
  path: '/commands-bash',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsCdRoute = DocsDocsCommandsCdRouteImport.update({
  id: '/commands-cd',
  path: '/commands-cd',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsClearRoute = DocsDocsCommandsClearRouteImport.update({
  id: '/commands-clear',
  path: '/commands-clear',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsCompactRoute = DocsDocsCommandsCompactRouteImport.update({
  id: '/commands-compact',
  path: '/commands-compact',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsEffortRoute = DocsDocsCommandsEffortRouteImport.update({
  id: '/commands-effort',
  path: '/commands-effort',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsExtensionRoute =
  DocsDocsCommandsExtensionRouteImport.update({
    id: '/commands-extension',
    path: '/commands-extension',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsCommandsFreeRoute = DocsDocsCommandsFreeRouteImport.update({
  id: '/commands-free',
  path: '/commands-free',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsHelpRoute = DocsDocsCommandsHelpRouteImport.update({
  id: '/commands-help',
  path: '/commands-help',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsInternetRoute =
  DocsDocsCommandsInternetRouteImport.update({
    id: '/commands-internet',
    path: '/commands-internet',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsCommandsMcpRoute = DocsDocsCommandsMcpRouteImport.update({
  id: '/commands-mcp',
  path: '/commands-mcp',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsModeRoute = DocsDocsCommandsModeRouteImport.update({
  id: '/commands-mode',
  path: '/commands-mode',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsModelRoute = DocsDocsCommandsModelRouteImport.update({
  id: '/commands-model',
  path: '/commands-model',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsNewRoute = DocsDocsCommandsNewRouteImport.update({
  id: '/commands-new',
  path: '/commands-new',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsQuitRoute = DocsDocsCommandsQuitRouteImport.update({
  id: '/commands-quit',
  path: '/commands-quit',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsRemoteRoute = DocsDocsCommandsRemoteRouteImport.update({
  id: '/commands-remote',
  path: '/commands-remote',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsRenameRoute = DocsDocsCommandsRenameRouteImport.update({
  id: '/commands-rename',
  path: '/commands-rename',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsResumeRoute = DocsDocsCommandsResumeRouteImport.update({
  id: '/commands-resume',
  path: '/commands-resume',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsSecurityRoute =
  DocsDocsCommandsSecurityRouteImport.update({
    id: '/commands-security',
    path: '/commands-security',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsCommandsSelectRoute = DocsDocsCommandsSelectRouteImport.update({
  id: '/commands-select',
  path: '/commands-select',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsSkillRoute = DocsDocsCommandsSkillRouteImport.update({
  id: '/commands-skill',
  path: '/commands-skill',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsStoreRoute = DocsDocsCommandsStoreRouteImport.update({
  id: '/commands-store',
  path: '/commands-store',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsTaskRoute = DocsDocsCommandsTaskRouteImport.update({
  id: '/commands-task',
  path: '/commands-task',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsTodoRoute = DocsDocsCommandsTodoRouteImport.update({
  id: '/commands-todo',
  path: '/commands-todo',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsCommandsUsageRoute = DocsDocsCommandsUsageRouteImport.update({
  id: '/commands-usage',
  path: '/commands-usage',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsGettingStartedRoute = DocsDocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsGuiRoute = DocsDocsGuiRouteImport.update({
  id: '/gui',
  path: '/gui',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsKeyboardShortcutsRoute =
  DocsDocsKeyboardShortcutsRouteImport.update({
    id: '/keyboard-shortcuts',
    path: '/keyboard-shortcuts',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsOverviewRoute = DocsDocsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsSettingsModelRoute = DocsDocsSettingsModelRouteImport.update({
  id: '/settings-model',
  path: '/settings-model',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsSettingsOauthRoute = DocsDocsSettingsOauthRouteImport.update({
  id: '/settings-oauth',
  path: '/settings-oauth',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsSettingsProviderRoute =
  DocsDocsSettingsProviderRouteImport.update({
    id: '/settings-provider',
    path: '/settings-provider',
    getParentRoute: () => DocsDocsRoute,
  } as any)
const DocsDocsTuiRoute = DocsDocsTuiRouteImport.update({
  id: '/tui',
  path: '/tui',
  getParentRoute: () => DocsDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/docs/architecture': typeof DocsDocsArchitectureRoute
  '/docs/commands-adddir': typeof DocsDocsCommandsAdddirRoute
  '/docs/commands-agents': typeof DocsDocsCommandsAgentsRoute
  '/docs/commands-all': typeof DocsDocsCommandsAllRoute
  '/docs/commands-attach': typeof DocsDocsCommandsAttachRoute
  '/docs/commands-bash': typeof DocsDocsCommandsBashRoute
  '/docs/commands-cd': typeof DocsDocsCommandsCdRoute
  '/docs/commands-clear': typeof DocsDocsCommandsClearRoute
  '/docs/commands-compact': typeof DocsDocsCommandsCompactRoute
  '/docs/commands-effort': typeof DocsDocsCommandsEffortRoute
  '/docs/commands-extension': typeof DocsDocsCommandsExtensionRoute
  '/docs/commands-free': typeof DocsDocsCommandsFreeRoute
  '/docs/commands-help': typeof DocsDocsCommandsHelpRoute
  '/docs/commands-internet': typeof DocsDocsCommandsInternetRoute
  '/docs/commands-mcp': typeof DocsDocsCommandsMcpRoute
  '/docs/commands-mode': typeof DocsDocsCommandsModeRoute
  '/docs/commands-model': typeof DocsDocsCommandsModelRoute
  '/docs/commands-new': typeof DocsDocsCommandsNewRoute
  '/docs/commands-quit': typeof DocsDocsCommandsQuitRoute
  '/docs/commands-remote': typeof DocsDocsCommandsRemoteRoute
  '/docs/commands-rename': typeof DocsDocsCommandsRenameRoute
  '/docs/commands-resume': typeof DocsDocsCommandsResumeRoute
  '/docs/commands-security': typeof DocsDocsCommandsSecurityRoute
  '/docs/commands-select': typeof DocsDocsCommandsSelectRoute
  '/docs/commands-skill': typeof DocsDocsCommandsSkillRoute
  '/docs/commands-store': typeof DocsDocsCommandsStoreRoute
  '/docs/commands-task': typeof DocsDocsCommandsTaskRoute
  '/docs/commands-todo': typeof DocsDocsCommandsTodoRoute
  '/docs/commands-usage': typeof DocsDocsCommandsUsageRoute
  '/docs/getting-started': typeof DocsDocsGettingStartedRoute
  '/docs/gui': typeof DocsDocsGuiRoute
  '/docs/keyboard-shortcuts': typeof DocsDocsKeyboardShortcutsRoute
  '/docs/overview': typeof DocsDocsOverviewRoute
  '/docs/settings-model': typeof DocsDocsSettingsModelRoute
  '/docs/settings-oauth': typeof DocsDocsSettingsOauthRoute
  '/docs/settings-provider': typeof DocsDocsSettingsProviderRoute
  '/docs/tui': typeof DocsDocsTuiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/docs/architecture': typeof DocsDocsArchitectureRoute
  '/docs/commands-adddir': typeof DocsDocsCommandsAdddirRoute
  '/docs/commands-agents': typeof DocsDocsCommandsAgentsRoute
  '/docs/commands-all': typeof DocsDocsCommandsAllRoute
  '/docs/commands-attach': typeof DocsDocsCommandsAttachRoute
  '/docs/commands-bash': typeof DocsDocsCommandsBashRoute
  '/docs/commands-cd': typeof DocsDocsCommandsCdRoute
  '/docs/commands-clear': typeof DocsDocsCommandsClearRoute
  '/docs/commands-compact': typeof DocsDocsCommandsCompactRoute
  '/docs/commands-effort': typeof DocsDocsCommandsEffortRoute
  '/docs/commands-extension': typeof DocsDocsCommandsExtensionRoute
  '/docs/commands-free': typeof DocsDocsCommandsFreeRoute
  '/docs/commands-help': typeof DocsDocsCommandsHelpRoute
  '/docs/commands-internet': typeof DocsDocsCommandsInternetRoute
  '/docs/commands-mcp': typeof DocsDocsCommandsMcpRoute
  '/docs/commands-mode': typeof DocsDocsCommandsModeRoute
  '/docs/commands-model': typeof DocsDocsCommandsModelRoute
  '/docs/commands-new': typeof DocsDocsCommandsNewRoute
  '/docs/commands-quit': typeof DocsDocsCommandsQuitRoute
  '/docs/commands-remote': typeof DocsDocsCommandsRemoteRoute
  '/docs/commands-rename': typeof DocsDocsCommandsRenameRoute
  '/docs/commands-resume': typeof DocsDocsCommandsResumeRoute
  '/docs/commands-security': typeof DocsDocsCommandsSecurityRoute
  '/docs/commands-select': typeof DocsDocsCommandsSelectRoute
  '/docs/commands-skill': typeof DocsDocsCommandsSkillRoute
  '/docs/commands-store': typeof DocsDocsCommandsStoreRoute
  '/docs/commands-task': typeof DocsDocsCommandsTaskRoute
  '/docs/commands-todo': typeof DocsDocsCommandsTodoRoute
  '/docs/commands-usage': typeof DocsDocsCommandsUsageRoute
  '/docs/getting-started': typeof DocsDocsGettingStartedRoute
  '/docs/gui': typeof DocsDocsGuiRoute
  '/docs/keyboard-shortcuts': typeof DocsDocsKeyboardShortcutsRoute
  '/docs/overview': typeof DocsDocsOverviewRoute
  '/docs/settings-model': typeof DocsDocsSettingsModelRoute
  '/docs/settings-oauth': typeof DocsDocsSettingsOauthRoute
  '/docs/settings-provider': typeof DocsDocsSettingsProviderRoute
  '/docs/tui': typeof DocsDocsTuiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteWithChildren
  '/_docs/docs': typeof DocsDocsRouteWithChildren
  '/_docs/docs/architecture': typeof DocsDocsArchitectureRoute
  '/_docs/docs/commands-adddir': typeof DocsDocsCommandsAdddirRoute
  '/_docs/docs/commands-agents': typeof DocsDocsCommandsAgentsRoute
  '/_docs/docs/commands-all': typeof DocsDocsCommandsAllRoute
  '/_docs/docs/commands-attach': typeof DocsDocsCommandsAttachRoute
  '/_docs/docs/commands-bash': typeof DocsDocsCommandsBashRoute
  '/_docs/docs/commands-cd': typeof DocsDocsCommandsCdRoute
  '/_docs/docs/commands-clear': typeof DocsDocsCommandsClearRoute
  '/_docs/docs/commands-compact': typeof DocsDocsCommandsCompactRoute
  '/_docs/docs/commands-effort': typeof DocsDocsCommandsEffortRoute
  '/_docs/docs/commands-extension': typeof DocsDocsCommandsExtensionRoute
  '/_docs/docs/commands-free': typeof DocsDocsCommandsFreeRoute
  '/_docs/docs/commands-help': typeof DocsDocsCommandsHelpRoute
  '/_docs/docs/commands-internet': typeof DocsDocsCommandsInternetRoute
  '/_docs/docs/commands-mcp': typeof DocsDocsCommandsMcpRoute
  '/_docs/docs/commands-mode': typeof DocsDocsCommandsModeRoute
  '/_docs/docs/commands-model': typeof DocsDocsCommandsModelRoute
  '/_docs/docs/commands-new': typeof DocsDocsCommandsNewRoute
  '/_docs/docs/commands-quit': typeof DocsDocsCommandsQuitRoute
  '/_docs/docs/commands-remote': typeof DocsDocsCommandsRemoteRoute
  '/_docs/docs/commands-rename': typeof DocsDocsCommandsRenameRoute
  '/_docs/docs/commands-resume': typeof DocsDocsCommandsResumeRoute
  '/_docs/docs/commands-security': typeof DocsDocsCommandsSecurityRoute
  '/_docs/docs/commands-select': typeof DocsDocsCommandsSelectRoute
  '/_docs/docs/commands-skill': typeof DocsDocsCommandsSkillRoute
  '/_docs/docs/commands-store': typeof DocsDocsCommandsStoreRoute
  '/_docs/docs/commands-task': typeof DocsDocsCommandsTaskRoute
  '/_docs/docs/commands-todo': typeof DocsDocsCommandsTodoRoute
  '/_docs/docs/commands-usage': typeof DocsDocsCommandsUsageRoute
  '/_docs/docs/getting-started': typeof DocsDocsGettingStartedRoute
  '/_docs/docs/gui': typeof DocsDocsGuiRoute
  '/_docs/docs/keyboard-shortcuts': typeof DocsDocsKeyboardShortcutsRoute
  '/_docs/docs/overview': typeof DocsDocsOverviewRoute
  '/_docs/docs/settings-model': typeof DocsDocsSettingsModelRoute
  '/_docs/docs/settings-oauth': typeof DocsDocsSettingsOauthRoute
  '/_docs/docs/settings-provider': typeof DocsDocsSettingsProviderRoute
  '/_docs/docs/tui': typeof DocsDocsTuiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/architecture'
    | '/docs/commands-adddir'
    | '/docs/commands-agents'
    | '/docs/commands-all'
    | '/docs/commands-attach'
    | '/docs/commands-bash'
    | '/docs/commands-cd'
    | '/docs/commands-clear'
    | '/docs/commands-compact'
    | '/docs/commands-effort'
    | '/docs/commands-extension'
    | '/docs/commands-free'
    | '/docs/commands-help'
    | '/docs/commands-internet'
    | '/docs/commands-mcp'
    | '/docs/commands-mode'
    | '/docs/commands-model'
    | '/docs/commands-new'
    | '/docs/commands-quit'
    | '/docs/commands-remote'
    | '/docs/commands-rename'
    | '/docs/commands-resume'
    | '/docs/commands-security'
    | '/docs/commands-select'
    | '/docs/commands-skill'
    | '/docs/commands-store'
    | '/docs/commands-task'
    | '/docs/commands-todo'
    | '/docs/commands-usage'
    | '/docs/getting-started'
    | '/docs/gui'
    | '/docs/keyboard-shortcuts'
    | '/docs/overview'
    | '/docs/settings-model'
    | '/docs/settings-oauth'
    | '/docs/settings-provider'
    | '/docs/tui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/architecture'
    | '/docs/commands-adddir'
    | '/docs/commands-agents'
    | '/docs/commands-all'
    | '/docs/commands-attach'
    | '/docs/commands-bash'
    | '/docs/commands-cd'
    | '/docs/commands-clear'
    | '/docs/commands-compact'
    | '/docs/commands-effort'
    | '/docs/commands-extension'
    | '/docs/commands-free'
    | '/docs/commands-help'
    | '/docs/commands-internet'
    | '/docs/commands-mcp'
    | '/docs/commands-mode'
    | '/docs/commands-model'
    | '/docs/commands-new'
    | '/docs/commands-quit'
    | '/docs/commands-remote'
    | '/docs/commands-rename'
    | '/docs/commands-resume'
    | '/docs/commands-security'
    | '/docs/commands-select'
    | '/docs/commands-skill'
    | '/docs/commands-store'
    | '/docs/commands-task'
    | '/docs/commands-todo'
    | '/docs/commands-usage'
    | '/docs/getting-started'
    | '/docs/gui'
    | '/docs/keyboard-shortcuts'
    | '/docs/overview'
    | '/docs/settings-model'
    | '/docs/settings-oauth'
    | '/docs/settings-provider'
    | '/docs/tui'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/_docs/docs'
    | '/_docs/docs/architecture'
    | '/_docs/docs/commands-adddir'
    | '/_docs/docs/commands-agents'
    | '/_docs/docs/commands-all'
    | '/_docs/docs/commands-attach'
    | '/_docs/docs/commands-bash'
    | '/_docs/docs/commands-cd'
    | '/_docs/docs/commands-clear'
    | '/_docs/docs/commands-compact'
    | '/_docs/docs/commands-effort'
    | '/_docs/docs/commands-extension'
    | '/_docs/docs/commands-free'
    | '/_docs/docs/commands-help'
    | '/_docs/docs/commands-internet'
    | '/_docs/docs/commands-mcp'
    | '/_docs/docs/commands-mode'
    | '/_docs/docs/commands-model'
    | '/_docs/docs/commands-new'
    | '/_docs/docs/commands-quit'
    | '/_docs/docs/commands-remote'
    | '/_docs/docs/commands-rename'
    | '/_docs/docs/commands-resume'
    | '/_docs/docs/commands-security'
    | '/_docs/docs/commands-select'
    | '/_docs/docs/commands-skill'
    | '/_docs/docs/commands-store'
    | '/_docs/docs/commands-task'
    | '/_docs/docs/commands-todo'
    | '/_docs/docs/commands-usage'
    | '/_docs/docs/getting-started'
    | '/_docs/docs/gui'
    | '/_docs/docs/keyboard-shortcuts'
    | '/_docs/docs/overview'
    | '/_docs/docs/settings-model'
    | '/_docs/docs/settings-oauth'
    | '/_docs/docs/settings-provider'
    | '/_docs/docs/tui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs': {
      id: '/_docs/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsDocsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/docs/architecture': {
      id: '/_docs/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsDocsArchitectureRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-adddir': {
      id: '/_docs/docs/commands-adddir'
      path: '/commands-adddir'
      fullPath: '/docs/commands-adddir'
      preLoaderRoute: typeof DocsDocsCommandsAdddirRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-agents': {
      id: '/_docs/docs/commands-agents'
      path: '/commands-agents'
      fullPath: '/docs/commands-agents'
      preLoaderRoute: typeof DocsDocsCommandsAgentsRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-all': {
      id: '/_docs/docs/commands-all'
      path: '/commands-all'
      fullPath: '/docs/commands-all'
      preLoaderRoute: typeof DocsDocsCommandsAllRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-attach': {
      id: '/_docs/docs/commands-attach'
      path: '/commands-attach'
      fullPath: '/docs/commands-attach'
      preLoaderRoute: typeof DocsDocsCommandsAttachRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-bash': {
      id: '/_docs/docs/commands-bash'
      path: '/commands-bash'
      fullPath: '/docs/commands-bash'
      preLoaderRoute: typeof DocsDocsCommandsBashRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-cd': {
      id: '/_docs/docs/commands-cd'
      path: '/commands-cd'
      fullPath: '/docs/commands-cd'
      preLoaderRoute: typeof DocsDocsCommandsCdRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-clear': {
      id: '/_docs/docs/commands-clear'
      path: '/commands-clear'
      fullPath: '/docs/commands-clear'
      preLoaderRoute: typeof DocsDocsCommandsClearRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-compact': {
      id: '/_docs/docs/commands-compact'
      path: '/commands-compact'
      fullPath: '/docs/commands-compact'
      preLoaderRoute: typeof DocsDocsCommandsCompactRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-effort': {
      id: '/_docs/docs/commands-effort'
      path: '/commands-effort'
      fullPath: '/docs/commands-effort'
      preLoaderRoute: typeof DocsDocsCommandsEffortRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-extension': {
      id: '/_docs/docs/commands-extension'
      path: '/commands-extension'
      fullPath: '/docs/commands-extension'
      preLoaderRoute: typeof DocsDocsCommandsExtensionRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-free': {
      id: '/_docs/docs/commands-free'
      path: '/commands-free'
      fullPath: '/docs/commands-free'
      preLoaderRoute: typeof DocsDocsCommandsFreeRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-help': {
      id: '/_docs/docs/commands-help'
      path: '/commands-help'
      fullPath: '/docs/commands-help'
      preLoaderRoute: typeof DocsDocsCommandsHelpRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-internet': {
      id: '/_docs/docs/commands-internet'
      path: '/commands-internet'
      fullPath: '/docs/commands-internet'
      preLoaderRoute: typeof DocsDocsCommandsInternetRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-mcp': {
      id: '/_docs/docs/commands-mcp'
      path: '/commands-mcp'
      fullPath: '/docs/commands-mcp'
      preLoaderRoute: typeof DocsDocsCommandsMcpRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-mode': {
      id: '/_docs/docs/commands-mode'
      path: '/commands-mode'
      fullPath: '/docs/commands-mode'
      preLoaderRoute: typeof DocsDocsCommandsModeRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-model': {
      id: '/_docs/docs/commands-model'
      path: '/commands-model'
      fullPath: '/docs/commands-model'
      preLoaderRoute: typeof DocsDocsCommandsModelRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-new': {
      id: '/_docs/docs/commands-new'
      path: '/commands-new'
      fullPath: '/docs/commands-new'
      preLoaderRoute: typeof DocsDocsCommandsNewRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-quit': {
      id: '/_docs/docs/commands-quit'
      path: '/commands-quit'
      fullPath: '/docs/commands-quit'
      preLoaderRoute: typeof DocsDocsCommandsQuitRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-remote': {
      id: '/_docs/docs/commands-remote'
      path: '/commands-remote'
      fullPath: '/docs/commands-remote'
      preLoaderRoute: typeof DocsDocsCommandsRemoteRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-rename': {
      id: '/_docs/docs/commands-rename'
      path: '/commands-rename'
      fullPath: '/docs/commands-rename'
      preLoaderRoute: typeof DocsDocsCommandsRenameRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-resume': {
      id: '/_docs/docs/commands-resume'
      path: '/commands-resume'
      fullPath: '/docs/commands-resume'
      preLoaderRoute: typeof DocsDocsCommandsResumeRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-security': {
      id: '/_docs/docs/commands-security'
      path: '/commands-security'
      fullPath: '/docs/commands-security'
      preLoaderRoute: typeof DocsDocsCommandsSecurityRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-select': {
      id: '/_docs/docs/commands-select'
      path: '/commands-select'
      fullPath: '/docs/commands-select'
      preLoaderRoute: typeof DocsDocsCommandsSelectRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-skill': {
      id: '/_docs/docs/commands-skill'
      path: '/commands-skill'
      fullPath: '/docs/commands-skill'
      preLoaderRoute: typeof DocsDocsCommandsSkillRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-store': {
      id: '/_docs/docs/commands-store'
      path: '/commands-store'
      fullPath: '/docs/commands-store'
      preLoaderRoute: typeof DocsDocsCommandsStoreRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-task': {
      id: '/_docs/docs/commands-task'
      path: '/commands-task'
      fullPath: '/docs/commands-task'
      preLoaderRoute: typeof DocsDocsCommandsTaskRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-todo': {
      id: '/_docs/docs/commands-todo'
      path: '/commands-todo'
      fullPath: '/docs/commands-todo'
      preLoaderRoute: typeof DocsDocsCommandsTodoRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/commands-usage': {
      id: '/_docs/docs/commands-usage'
      path: '/commands-usage'
      fullPath: '/docs/commands-usage'
      preLoaderRoute: typeof DocsDocsCommandsUsageRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/getting-started': {
      id: '/_docs/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsDocsGettingStartedRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/gui': {
      id: '/_docs/docs/gui'
      path: '/gui'
      fullPath: '/docs/gui'
      preLoaderRoute: typeof DocsDocsGuiRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/keyboard-shortcuts': {
      id: '/_docs/docs/keyboard-shortcuts'
      path: '/keyboard-shortcuts'
      fullPath: '/docs/keyboard-shortcuts'
      preLoaderRoute: typeof DocsDocsKeyboardShortcutsRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/overview': {
      id: '/_docs/docs/overview'
      path: '/overview'
      fullPath: '/docs/overview'
      preLoaderRoute: typeof DocsDocsOverviewRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/settings-model': {
      id: '/_docs/docs/settings-model'
      path: '/settings-model'
      fullPath: '/docs/settings-model'
      preLoaderRoute: typeof DocsDocsSettingsModelRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/settings-oauth': {
      id: '/_docs/docs/settings-oauth'
      path: '/settings-oauth'
      fullPath: '/docs/settings-oauth'
      preLoaderRoute: typeof DocsDocsSettingsOauthRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/settings-provider': {
      id: '/_docs/docs/settings-provider'
      path: '/settings-provider'
      fullPath: '/docs/settings-provider'
      preLoaderRoute: typeof DocsDocsSettingsProviderRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/tui': {
      id: '/_docs/docs/tui'
      path: '/tui'
      fullPath: '/docs/tui'
      preLoaderRoute: typeof DocsDocsTuiRouteImport
      parentRoute: typeof DocsDocsRoute
    }
  }
}

interface DocsDocsRouteChildren {
  DocsDocsArchitectureRoute: typeof DocsDocsArchitectureRoute
  DocsDocsCommandsAdddirRoute: typeof DocsDocsCommandsAdddirRoute
  DocsDocsCommandsAgentsRoute: typeof DocsDocsCommandsAgentsRoute
  DocsDocsCommandsAllRoute: typeof DocsDocsCommandsAllRoute
  DocsDocsCommandsAttachRoute: typeof DocsDocsCommandsAttachRoute
  DocsDocsCommandsBashRoute: typeof DocsDocsCommandsBashRoute
  DocsDocsCommandsCdRoute: typeof DocsDocsCommandsCdRoute
  DocsDocsCommandsClearRoute: typeof DocsDocsCommandsClearRoute
  DocsDocsCommandsCompactRoute: typeof DocsDocsCommandsCompactRoute
  DocsDocsCommandsEffortRoute: typeof DocsDocsCommandsEffortRoute
  DocsDocsCommandsExtensionRoute: typeof DocsDocsCommandsExtensionRoute
  DocsDocsCommandsFreeRoute: typeof DocsDocsCommandsFreeRoute
  DocsDocsCommandsHelpRoute: typeof DocsDocsCommandsHelpRoute
  DocsDocsCommandsInternetRoute: typeof DocsDocsCommandsInternetRoute
  DocsDocsCommandsMcpRoute: typeof DocsDocsCommandsMcpRoute
  DocsDocsCommandsModeRoute: typeof DocsDocsCommandsModeRoute
  DocsDocsCommandsModelRoute: typeof DocsDocsCommandsModelRoute
  DocsDocsCommandsNewRoute: typeof DocsDocsCommandsNewRoute
  DocsDocsCommandsQuitRoute: typeof DocsDocsCommandsQuitRoute
  DocsDocsCommandsRemoteRoute: typeof DocsDocsCommandsRemoteRoute
  DocsDocsCommandsRenameRoute: typeof DocsDocsCommandsRenameRoute
  DocsDocsCommandsResumeRoute: typeof DocsDocsCommandsResumeRoute
  DocsDocsCommandsSecurityRoute: typeof DocsDocsCommandsSecurityRoute
  DocsDocsCommandsSelectRoute: typeof DocsDocsCommandsSelectRoute
  DocsDocsCommandsSkillRoute: typeof DocsDocsCommandsSkillRoute
  DocsDocsCommandsStoreRoute: typeof DocsDocsCommandsStoreRoute
  DocsDocsCommandsTaskRoute: typeof DocsDocsCommandsTaskRoute
  DocsDocsCommandsTodoRoute: typeof DocsDocsCommandsTodoRoute
  DocsDocsCommandsUsageRoute: typeof DocsDocsCommandsUsageRoute
  DocsDocsGettingStartedRoute: typeof DocsDocsGettingStartedRoute
  DocsDocsGuiRoute: typeof DocsDocsGuiRoute
  DocsDocsKeyboardShortcutsRoute: typeof DocsDocsKeyboardShortcutsRoute
  DocsDocsOverviewRoute: typeof DocsDocsOverviewRoute
  DocsDocsSettingsModelRoute: typeof DocsDocsSettingsModelRoute
  DocsDocsSettingsOauthRoute: typeof DocsDocsSettingsOauthRoute
  DocsDocsSettingsProviderRoute: typeof DocsDocsSettingsProviderRoute
  DocsDocsTuiRoute: typeof DocsDocsTuiRoute
}

const DocsDocsRouteChildren: DocsDocsRouteChildren = {
  DocsDocsArchitectureRoute: DocsDocsArchitectureRoute,
  DocsDocsCommandsAdddirRoute: DocsDocsCommandsAdddirRoute,
  DocsDocsCommandsAgentsRoute: DocsDocsCommandsAgentsRoute,
  DocsDocsCommandsAllRoute: DocsDocsCommandsAllRoute,
  DocsDocsCommandsAttachRoute: DocsDocsCommandsAttachRoute,
  DocsDocsCommandsBashRoute: DocsDocsCommandsBashRoute,
  DocsDocsCommandsCdRoute: DocsDocsCommandsCdRoute,
  DocsDocsCommandsClearRoute: DocsDocsCommandsClearRoute,
  DocsDocsCommandsCompactRoute: DocsDocsCommandsCompactRoute,
  DocsDocsCommandsEffortRoute: DocsDocsCommandsEffortRoute,
  DocsDocsCommandsExtensionRoute: DocsDocsCommandsExtensionRoute,
  DocsDocsCommandsFreeRoute: DocsDocsCommandsFreeRoute,
  DocsDocsCommandsHelpRoute: DocsDocsCommandsHelpRoute,
  DocsDocsCommandsInternetRoute: DocsDocsCommandsInternetRoute,
  DocsDocsCommandsMcpRoute: DocsDocsCommandsMcpRoute,
  DocsDocsCommandsModeRoute: DocsDocsCommandsModeRoute,
  DocsDocsCommandsModelRoute: DocsDocsCommandsModelRoute,
  DocsDocsCommandsNewRoute: DocsDocsCommandsNewRoute,
  DocsDocsCommandsQuitRoute: DocsDocsCommandsQuitRoute,
  DocsDocsCommandsRemoteRoute: DocsDocsCommandsRemoteRoute,
  DocsDocsCommandsRenameRoute: DocsDocsCommandsRenameRoute,
  DocsDocsCommandsResumeRoute: DocsDocsCommandsResumeRoute,
  DocsDocsCommandsSecurityRoute: DocsDocsCommandsSecurityRoute,
  DocsDocsCommandsSelectRoute: DocsDocsCommandsSelectRoute,
  DocsDocsCommandsSkillRoute: DocsDocsCommandsSkillRoute,
  DocsDocsCommandsStoreRoute: DocsDocsCommandsStoreRoute,
  DocsDocsCommandsTaskRoute: DocsDocsCommandsTaskRoute,
  DocsDocsCommandsTodoRoute: DocsDocsCommandsTodoRoute,
  DocsDocsCommandsUsageRoute: DocsDocsCommandsUsageRoute,
  DocsDocsGettingStartedRoute: DocsDocsGettingStartedRoute,
  DocsDocsGuiRoute: DocsDocsGuiRoute,
  DocsDocsKeyboardShortcutsRoute: DocsDocsKeyboardShortcutsRoute,
  DocsDocsOverviewRoute: DocsDocsOverviewRoute,
  DocsDocsSettingsModelRoute: DocsDocsSettingsModelRoute,
  DocsDocsSettingsOauthRoute: DocsDocsSettingsOauthRoute,
  DocsDocsSettingsProviderRoute: DocsDocsSettingsProviderRoute,
  DocsDocsTuiRoute: DocsDocsTuiRoute,
}

const DocsDocsRouteWithChildren = DocsDocsRoute._addFileChildren(
  DocsDocsRouteChildren,
)

interface DocsRouteChildren {
  DocsDocsRoute: typeof DocsDocsRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsRoute: DocsDocsRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
