/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as DocsDocsRouteImport } from './routes/_docs/docs'
import { Route as DocsDocsArchitectureRouteImport } from './routes/_docs/docs/architecture'
import { Route as DocsDocsGettingStartedRouteImport } from './routes/_docs/docs/getting-started'
import { Route as DocsDocsGuiRouteImport } from './routes/_docs/docs/gui'
import { Route as DocsDocsOverviewRouteImport } from './routes/_docs/docs/overview'
import { Route as DocsDocsTuiRouteImport } from './routes/_docs/docs/tui'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsRoute = DocsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocsArchitectureRoute = DocsDocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsGettingStartedRoute = DocsDocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsGuiRoute = DocsDocsGuiRouteImport.update({
  id: '/gui',
  path: '/gui',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsOverviewRoute = DocsDocsOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsTuiRoute = DocsDocsTuiRouteImport.update({
  id: '/tui',
  path: '/tui',
  getParentRoute: () => DocsDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/docs/architecture': typeof DocsDocsArchitectureRoute
  '/docs/getting-started': typeof DocsDocsGettingStartedRoute
  '/docs/gui': typeof DocsDocsGuiRoute
  '/docs/overview': typeof DocsDocsOverviewRoute
  '/docs/tui': typeof DocsDocsTuiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/docs/architecture': typeof DocsDocsArchitectureRoute
  '/docs/getting-started': typeof DocsDocsGettingStartedRoute
  '/docs/gui': typeof DocsDocsGuiRoute
  '/docs/overview': typeof DocsDocsOverviewRoute
  '/docs/tui': typeof DocsDocsTuiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteWithChildren
  '/_docs/docs': typeof DocsDocsRouteWithChildren
  '/_docs/docs/architecture': typeof DocsDocsArchitectureRoute
  '/_docs/docs/getting-started': typeof DocsDocsGettingStartedRoute
  '/_docs/docs/gui': typeof DocsDocsGuiRoute
  '/_docs/docs/overview': typeof DocsDocsOverviewRoute
  '/_docs/docs/tui': typeof DocsDocsTuiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/architecture'
    | '/docs/getting-started'
    | '/docs/gui'
    | '/docs/overview'
    | '/docs/tui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/architecture'
    | '/docs/getting-started'
    | '/docs/gui'
    | '/docs/overview'
    | '/docs/tui'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/_docs/docs'
    | '/_docs/docs/architecture'
    | '/_docs/docs/getting-started'
    | '/_docs/docs/gui'
    | '/_docs/docs/overview'
    | '/_docs/docs/tui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs': {
      id: '/_docs/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsDocsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/docs/architecture': {
      id: '/_docs/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsDocsArchitectureRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/getting-started': {
      id: '/_docs/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsDocsGettingStartedRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/gui': {
      id: '/_docs/docs/gui'
      path: '/gui'
      fullPath: '/docs/gui'
      preLoaderRoute: typeof DocsDocsGuiRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/overview': {
      id: '/_docs/docs/overview'
      path: '/overview'
      fullPath: '/docs/overview'
      preLoaderRoute: typeof DocsDocsOverviewRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/tui': {
      id: '/_docs/docs/tui'
      path: '/tui'
      fullPath: '/docs/tui'
      preLoaderRoute: typeof DocsDocsTuiRouteImport
      parentRoute: typeof DocsDocsRoute
    }
  }
}

interface DocsDocsRouteChildren {
  DocsDocsArchitectureRoute: typeof DocsDocsArchitectureRoute
  DocsDocsGettingStartedRoute: typeof DocsDocsGettingStartedRoute
  DocsDocsGuiRoute: typeof DocsDocsGuiRoute
  DocsDocsOverviewRoute: typeof DocsDocsOverviewRoute
  DocsDocsTuiRoute: typeof DocsDocsTuiRoute
}

const DocsDocsRouteChildren: DocsDocsRouteChildren = {
  DocsDocsArchitectureRoute: DocsDocsArchitectureRoute,
  DocsDocsGettingStartedRoute: DocsDocsGettingStartedRoute,
  DocsDocsGuiRoute: DocsDocsGuiRoute,
  DocsDocsOverviewRoute: DocsDocsOverviewRoute,
  DocsDocsTuiRoute: DocsDocsTuiRoute,
}

const DocsDocsRouteWithChildren = DocsDocsRoute._addFileChildren(
  DocsDocsRouteChildren,
)

interface DocsRouteChildren {
  DocsDocsRoute: typeof DocsDocsRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsRoute: DocsDocsRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
