/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as DocsDocsRouteImport } from './routes/_docs/docs'
import { Route as DocsGuiRouteImport } from './routes/_docs/gui'
import { Route as DocsTuiRouteImport } from './routes/_docs/tui'
import { Route as DocsWelcomeRouteImport } from './routes/_docs/welcome'
import { Route as DocsDocsIndexRouteImport } from './routes/_docs/docs/index'
import { Route as DocsDocsSlugRouteImport } from './routes/_docs/docs/$slug'
import { Route as DocsGuiIndexRouteImport } from './routes/_docs/gui/index'
import { Route as DocsGuiAnalyticsRouteImport } from './routes/_docs/gui/analytics'
import { Route as DocsGuiChatComposerRouteImport } from './routes/_docs/gui/chat-composer'
import { Route as DocsGuiCodeEditorRouteImport } from './routes/_docs/gui/code-editor'
import { Route as DocsGuiExtensionsRouteImport } from './routes/_docs/gui/extensions'
import { Route as DocsGuiFirstRunRouteImport } from './routes/_docs/gui/first-run'
import { Route as DocsGuiGitDiffRouteImport } from './routes/_docs/gui/git-diff'
import { Route as DocsGuiImportGraphRouteImport } from './routes/_docs/gui/import-graph'
import { Route as DocsGuiLayoutRouteImport } from './routes/_docs/gui/layout'
import { Route as DocsGuiOauthRouteImport } from './routes/_docs/gui/oauth'
import { Route as DocsGuiProviderModelRouteImport } from './routes/_docs/gui/provider-model'
import { Route as DocsTuiIndexRouteImport } from './routes/_docs/tui/index'
import { Route as DocsTuiCommandsAdddirRouteImport } from './routes/_docs/tui/commands-adddir'
import { Route as DocsTuiCommandsAgentsRouteImport } from './routes/_docs/tui/commands-agents'
import { Route as DocsTuiCommandsAllRouteImport } from './routes/_docs/tui/commands-all'
import { Route as DocsTuiCommandsAttachRouteImport } from './routes/_docs/tui/commands-attach'
import { Route as DocsTuiCommandsBashRouteImport } from './routes/_docs/tui/commands-bash'
import { Route as DocsTuiCommandsCdRouteImport } from './routes/_docs/tui/commands-cd'
import { Route as DocsTuiCommandsClearRouteImport } from './routes/_docs/tui/commands-clear'
import { Route as DocsTuiCommandsCompactRouteImport } from './routes/_docs/tui/commands-compact'
import { Route as DocsTuiCommandsEffortRouteImport } from './routes/_docs/tui/commands-effort'
import { Route as DocsTuiCommandsExtensionRouteImport } from './routes/_docs/tui/commands-extension'
import { Route as DocsTuiCommandsFreeRouteImport } from './routes/_docs/tui/commands-free'
import { Route as DocsTuiCommandsHelpRouteImport } from './routes/_docs/tui/commands-help'
import { Route as DocsTuiCommandsInternetRouteImport } from './routes/_docs/tui/commands-internet'
import { Route as DocsTuiCommandsMcpRouteImport } from './routes/_docs/tui/commands-mcp'
import { Route as DocsTuiCommandsModeRouteImport } from './routes/_docs/tui/commands-mode'
import { Route as DocsTuiCommandsModelRouteImport } from './routes/_docs/tui/commands-model'
import { Route as DocsTuiCommandsNewRouteImport } from './routes/_docs/tui/commands-new'
import { Route as DocsTuiCommandsQuitRouteImport } from './routes/_docs/tui/commands-quit'
import { Route as DocsTuiCommandsRemoteRouteImport } from './routes/_docs/tui/commands-remote'
import { Route as DocsTuiCommandsRenameRouteImport } from './routes/_docs/tui/commands-rename'
import { Route as DocsTuiCommandsResumeRouteImport } from './routes/_docs/tui/commands-resume'
import { Route as DocsTuiCommandsSecurityRouteImport } from './routes/_docs/tui/commands-security'
import { Route as DocsTuiCommandsSelectRouteImport } from './routes/_docs/tui/commands-select'
import { Route as DocsTuiCommandsSkillRouteImport } from './routes/_docs/tui/commands-skill'
import { Route as DocsTuiCommandsStoreRouteImport } from './routes/_docs/tui/commands-store'
import { Route as DocsTuiCommandsTaskRouteImport } from './routes/_docs/tui/commands-task'
import { Route as DocsTuiCommandsTodoRouteImport } from './routes/_docs/tui/commands-todo'
import { Route as DocsTuiCommandsUsageRouteImport } from './routes/_docs/tui/commands-usage'
import { Route as DocsTuiFirstRunRouteImport } from './routes/_docs/tui/first-run'
import { Route as DocsTuiKeyboardShortcutsRouteImport } from './routes/_docs/tui/keyboard-shortcuts'
import { Route as DocsTuiOauthRouteImport } from './routes/_docs/tui/oauth'
import { Route as DocsTuiProviderModelRouteImport } from './routes/_docs/tui/provider-model'
import { Route as DocsTuiSettingsAppearanceRouteImport } from './routes/_docs/tui/settings-appearance'
import { Route as DocsTuiSettingsGeneralRouteImport } from './routes/_docs/tui/settings-general'
import { Route as DocsTuiSettingsModelRouteImport } from './routes/_docs/tui/settings-model'
import { Route as DocsTuiSettingsOauthRouteImport } from './routes/_docs/tui/settings-oauth'
import { Route as DocsTuiSettingsProviderRouteImport } from './routes/_docs/tui/settings-provider'
import { Route as DocsWelcomeIndexRouteImport } from './routes/_docs/welcome/index'
import { Route as DocsWelcomeArchitectureRouteImport } from './routes/_docs/welcome/architecture'
import { Route as DocsWelcomeGettingStartedRouteImport } from './routes/_docs/welcome/getting-started'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsRoute = DocsDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuiRoute = DocsGuiRouteImport.update({
  id: '/gui',
  path: '/gui',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTuiRoute = DocsTuiRouteImport.update({
  id: '/tui',
  path: '/tui',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWelcomeRoute = DocsWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDocsIndexRoute = DocsDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsDocsSlugRoute = DocsDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsDocsRoute,
} as any)
const DocsGuiIndexRoute = DocsGuiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiAnalyticsRoute = DocsGuiAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiChatComposerRoute = DocsGuiChatComposerRouteImport.update({
  id: '/chat-composer',
  path: '/chat-composer',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiCodeEditorRoute = DocsGuiCodeEditorRouteImport.update({
  id: '/code-editor',
  path: '/code-editor',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiExtensionsRoute = DocsGuiExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiFirstRunRoute = DocsGuiFirstRunRouteImport.update({
  id: '/first-run',
  path: '/first-run',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiGitDiffRoute = DocsGuiGitDiffRouteImport.update({
  id: '/git-diff',
  path: '/git-diff',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiImportGraphRoute = DocsGuiImportGraphRouteImport.update({
  id: '/import-graph',
  path: '/import-graph',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiLayoutRoute = DocsGuiLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiOauthRoute = DocsGuiOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsGuiProviderModelRoute = DocsGuiProviderModelRouteImport.update({
  id: '/provider-model',
  path: '/provider-model',
  getParentRoute: () => DocsGuiRoute,
} as any)
const DocsTuiIndexRoute = DocsTuiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsAdddirRoute = DocsTuiCommandsAdddirRouteImport.update({
  id: '/commands-adddir',
  path: '/commands-adddir',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsAgentsRoute = DocsTuiCommandsAgentsRouteImport.update({
  id: '/commands-agents',
  path: '/commands-agents',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsAllRoute = DocsTuiCommandsAllRouteImport.update({
  id: '/commands-all',
  path: '/commands-all',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsAttachRoute = DocsTuiCommandsAttachRouteImport.update({
  id: '/commands-attach',
  path: '/commands-attach',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsBashRoute = DocsTuiCommandsBashRouteImport.update({
  id: '/commands-bash',
  path: '/commands-bash',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsCdRoute = DocsTuiCommandsCdRouteImport.update({
  id: '/commands-cd',
  path: '/commands-cd',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsClearRoute = DocsTuiCommandsClearRouteImport.update({
  id: '/commands-clear',
  path: '/commands-clear',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsCompactRoute = DocsTuiCommandsCompactRouteImport.update({
  id: '/commands-compact',
  path: '/commands-compact',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsEffortRoute = DocsTuiCommandsEffortRouteImport.update({
  id: '/commands-effort',
  path: '/commands-effort',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsExtensionRoute =
  DocsTuiCommandsExtensionRouteImport.update({
    id: '/commands-extension',
    path: '/commands-extension',
    getParentRoute: () => DocsTuiRoute,
  } as any)
const DocsTuiCommandsFreeRoute = DocsTuiCommandsFreeRouteImport.update({
  id: '/commands-free',
  path: '/commands-free',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsHelpRoute = DocsTuiCommandsHelpRouteImport.update({
  id: '/commands-help',
  path: '/commands-help',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsInternetRoute = DocsTuiCommandsInternetRouteImport.update({
  id: '/commands-internet',
  path: '/commands-internet',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsMcpRoute = DocsTuiCommandsMcpRouteImport.update({
  id: '/commands-mcp',
  path: '/commands-mcp',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsModeRoute = DocsTuiCommandsModeRouteImport.update({
  id: '/commands-mode',
  path: '/commands-mode',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsModelRoute = DocsTuiCommandsModelRouteImport.update({
  id: '/commands-model',
  path: '/commands-model',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsNewRoute = DocsTuiCommandsNewRouteImport.update({
  id: '/commands-new',
  path: '/commands-new',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsQuitRoute = DocsTuiCommandsQuitRouteImport.update({
  id: '/commands-quit',
  path: '/commands-quit',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsRemoteRoute = DocsTuiCommandsRemoteRouteImport.update({
  id: '/commands-remote',
  path: '/commands-remote',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsRenameRoute = DocsTuiCommandsRenameRouteImport.update({
  id: '/commands-rename',
  path: '/commands-rename',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsResumeRoute = DocsTuiCommandsResumeRouteImport.update({
  id: '/commands-resume',
  path: '/commands-resume',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsSecurityRoute = DocsTuiCommandsSecurityRouteImport.update({
  id: '/commands-security',
  path: '/commands-security',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsSelectRoute = DocsTuiCommandsSelectRouteImport.update({
  id: '/commands-select',
  path: '/commands-select',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsSkillRoute = DocsTuiCommandsSkillRouteImport.update({
  id: '/commands-skill',
  path: '/commands-skill',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsStoreRoute = DocsTuiCommandsStoreRouteImport.update({
  id: '/commands-store',
  path: '/commands-store',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsTaskRoute = DocsTuiCommandsTaskRouteImport.update({
  id: '/commands-task',
  path: '/commands-task',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsTodoRoute = DocsTuiCommandsTodoRouteImport.update({
  id: '/commands-todo',
  path: '/commands-todo',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiCommandsUsageRoute = DocsTuiCommandsUsageRouteImport.update({
  id: '/commands-usage',
  path: '/commands-usage',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiFirstRunRoute = DocsTuiFirstRunRouteImport.update({
  id: '/first-run',
  path: '/first-run',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiKeyboardShortcutsRoute =
  DocsTuiKeyboardShortcutsRouteImport.update({
    id: '/keyboard-shortcuts',
    path: '/keyboard-shortcuts',
    getParentRoute: () => DocsTuiRoute,
  } as any)
const DocsTuiOauthRoute = DocsTuiOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiProviderModelRoute = DocsTuiProviderModelRouteImport.update({
  id: '/provider-model',
  path: '/provider-model',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiSettingsAppearanceRoute =
  DocsTuiSettingsAppearanceRouteImport.update({
    id: '/settings-appearance',
    path: '/settings-appearance',
    getParentRoute: () => DocsTuiRoute,
  } as any)
const DocsTuiSettingsGeneralRoute = DocsTuiSettingsGeneralRouteImport.update({
  id: '/settings-general',
  path: '/settings-general',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiSettingsModelRoute = DocsTuiSettingsModelRouteImport.update({
  id: '/settings-model',
  path: '/settings-model',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiSettingsOauthRoute = DocsTuiSettingsOauthRouteImport.update({
  id: '/settings-oauth',
  path: '/settings-oauth',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsTuiSettingsProviderRoute = DocsTuiSettingsProviderRouteImport.update({
  id: '/settings-provider',
  path: '/settings-provider',
  getParentRoute: () => DocsTuiRoute,
} as any)
const DocsWelcomeIndexRoute = DocsWelcomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsWelcomeRoute,
} as any)
const DocsWelcomeArchitectureRoute = DocsWelcomeArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsWelcomeRoute,
} as any)
const DocsWelcomeGettingStartedRoute =
  DocsWelcomeGettingStartedRouteImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => DocsWelcomeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsDocsRouteWithChildren
  '/gui': typeof DocsGuiRouteWithChildren
  '/tui': typeof DocsTuiRouteWithChildren
  '/welcome': typeof DocsWelcomeRouteWithChildren
  '/docs/$slug': typeof DocsDocsSlugRoute
  '/gui/analytics': typeof DocsGuiAnalyticsRoute
  '/gui/chat-composer': typeof DocsGuiChatComposerRoute
  '/gui/code-editor': typeof DocsGuiCodeEditorRoute
  '/gui/extensions': typeof DocsGuiExtensionsRoute
  '/gui/first-run': typeof DocsGuiFirstRunRoute
  '/gui/git-diff': typeof DocsGuiGitDiffRoute
  '/gui/import-graph': typeof DocsGuiImportGraphRoute
  '/gui/layout': typeof DocsGuiLayoutRoute
  '/gui/oauth': typeof DocsGuiOauthRoute
  '/gui/provider-model': typeof DocsGuiProviderModelRoute
  '/tui/commands-adddir': typeof DocsTuiCommandsAdddirRoute
  '/tui/commands-agents': typeof DocsTuiCommandsAgentsRoute
  '/tui/commands-all': typeof DocsTuiCommandsAllRoute
  '/tui/commands-attach': typeof DocsTuiCommandsAttachRoute
  '/tui/commands-bash': typeof DocsTuiCommandsBashRoute
  '/tui/commands-cd': typeof DocsTuiCommandsCdRoute
  '/tui/commands-clear': typeof DocsTuiCommandsClearRoute
  '/tui/commands-compact': typeof DocsTuiCommandsCompactRoute
  '/tui/commands-effort': typeof DocsTuiCommandsEffortRoute
  '/tui/commands-extension': typeof DocsTuiCommandsExtensionRoute
  '/tui/commands-free': typeof DocsTuiCommandsFreeRoute
  '/tui/commands-help': typeof DocsTuiCommandsHelpRoute
  '/tui/commands-internet': typeof DocsTuiCommandsInternetRoute
  '/tui/commands-mcp': typeof DocsTuiCommandsMcpRoute
  '/tui/commands-mode': typeof DocsTuiCommandsModeRoute
  '/tui/commands-model': typeof DocsTuiCommandsModelRoute
  '/tui/commands-new': typeof DocsTuiCommandsNewRoute
  '/tui/commands-quit': typeof DocsTuiCommandsQuitRoute
  '/tui/commands-remote': typeof DocsTuiCommandsRemoteRoute
  '/tui/commands-rename': typeof DocsTuiCommandsRenameRoute
  '/tui/commands-resume': typeof DocsTuiCommandsResumeRoute
  '/tui/commands-security': typeof DocsTuiCommandsSecurityRoute
  '/tui/commands-select': typeof DocsTuiCommandsSelectRoute
  '/tui/commands-skill': typeof DocsTuiCommandsSkillRoute
  '/tui/commands-store': typeof DocsTuiCommandsStoreRoute
  '/tui/commands-task': typeof DocsTuiCommandsTaskRoute
  '/tui/commands-todo': typeof DocsTuiCommandsTodoRoute
  '/tui/commands-usage': typeof DocsTuiCommandsUsageRoute
  '/tui/first-run': typeof DocsTuiFirstRunRoute
  '/tui/keyboard-shortcuts': typeof DocsTuiKeyboardShortcutsRoute
  '/tui/oauth': typeof DocsTuiOauthRoute
  '/tui/provider-model': typeof DocsTuiProviderModelRoute
  '/tui/settings-appearance': typeof DocsTuiSettingsAppearanceRoute
  '/tui/settings-general': typeof DocsTuiSettingsGeneralRoute
  '/tui/settings-model': typeof DocsTuiSettingsModelRoute
  '/tui/settings-oauth': typeof DocsTuiSettingsOauthRoute
  '/tui/settings-provider': typeof DocsTuiSettingsProviderRoute
  '/welcome/architecture': typeof DocsWelcomeArchitectureRoute
  '/welcome/getting-started': typeof DocsWelcomeGettingStartedRoute
  '/docs/': typeof DocsDocsIndexRoute
  '/gui/': typeof DocsGuiIndexRoute
  '/tui/': typeof DocsTuiIndexRoute
  '/welcome/': typeof DocsWelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$slug': typeof DocsDocsSlugRoute
  '/gui/analytics': typeof DocsGuiAnalyticsRoute
  '/gui/chat-composer': typeof DocsGuiChatComposerRoute
  '/gui/code-editor': typeof DocsGuiCodeEditorRoute
  '/gui/extensions': typeof DocsGuiExtensionsRoute
  '/gui/first-run': typeof DocsGuiFirstRunRoute
  '/gui/git-diff': typeof DocsGuiGitDiffRoute
  '/gui/import-graph': typeof DocsGuiImportGraphRoute
  '/gui/layout': typeof DocsGuiLayoutRoute
  '/gui/oauth': typeof DocsGuiOauthRoute
  '/gui/provider-model': typeof DocsGuiProviderModelRoute
  '/tui/commands-adddir': typeof DocsTuiCommandsAdddirRoute
  '/tui/commands-agents': typeof DocsTuiCommandsAgentsRoute
  '/tui/commands-all': typeof DocsTuiCommandsAllRoute
  '/tui/commands-attach': typeof DocsTuiCommandsAttachRoute
  '/tui/commands-bash': typeof DocsTuiCommandsBashRoute
  '/tui/commands-cd': typeof DocsTuiCommandsCdRoute
  '/tui/commands-clear': typeof DocsTuiCommandsClearRoute
  '/tui/commands-compact': typeof DocsTuiCommandsCompactRoute
  '/tui/commands-effort': typeof DocsTuiCommandsEffortRoute
  '/tui/commands-extension': typeof DocsTuiCommandsExtensionRoute
  '/tui/commands-free': typeof DocsTuiCommandsFreeRoute
  '/tui/commands-help': typeof DocsTuiCommandsHelpRoute
  '/tui/commands-internet': typeof DocsTuiCommandsInternetRoute
  '/tui/commands-mcp': typeof DocsTuiCommandsMcpRoute
  '/tui/commands-mode': typeof DocsTuiCommandsModeRoute
  '/tui/commands-model': typeof DocsTuiCommandsModelRoute
  '/tui/commands-new': typeof DocsTuiCommandsNewRoute
  '/tui/commands-quit': typeof DocsTuiCommandsQuitRoute
  '/tui/commands-remote': typeof DocsTuiCommandsRemoteRoute
  '/tui/commands-rename': typeof DocsTuiCommandsRenameRoute
  '/tui/commands-resume': typeof DocsTuiCommandsResumeRoute
  '/tui/commands-security': typeof DocsTuiCommandsSecurityRoute
  '/tui/commands-select': typeof DocsTuiCommandsSelectRoute
  '/tui/commands-skill': typeof DocsTuiCommandsSkillRoute
  '/tui/commands-store': typeof DocsTuiCommandsStoreRoute
  '/tui/commands-task': typeof DocsTuiCommandsTaskRoute
  '/tui/commands-todo': typeof DocsTuiCommandsTodoRoute
  '/tui/commands-usage': typeof DocsTuiCommandsUsageRoute
  '/tui/first-run': typeof DocsTuiFirstRunRoute
  '/tui/keyboard-shortcuts': typeof DocsTuiKeyboardShortcutsRoute
  '/tui/oauth': typeof DocsTuiOauthRoute
  '/tui/provider-model': typeof DocsTuiProviderModelRoute
  '/tui/settings-appearance': typeof DocsTuiSettingsAppearanceRoute
  '/tui/settings-general': typeof DocsTuiSettingsGeneralRoute
  '/tui/settings-model': typeof DocsTuiSettingsModelRoute
  '/tui/settings-oauth': typeof DocsTuiSettingsOauthRoute
  '/tui/settings-provider': typeof DocsTuiSettingsProviderRoute
  '/welcome/architecture': typeof DocsWelcomeArchitectureRoute
  '/welcome/getting-started': typeof DocsWelcomeGettingStartedRoute
  '/docs': typeof DocsDocsIndexRoute
  '/gui': typeof DocsGuiIndexRoute
  '/tui': typeof DocsTuiIndexRoute
  '/welcome': typeof DocsWelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docs': typeof DocsRouteWithChildren
  '/_docs/docs': typeof DocsDocsRouteWithChildren
  '/_docs/gui': typeof DocsGuiRouteWithChildren
  '/_docs/tui': typeof DocsTuiRouteWithChildren
  '/_docs/welcome': typeof DocsWelcomeRouteWithChildren
  '/_docs/docs/$slug': typeof DocsDocsSlugRoute
  '/_docs/gui/analytics': typeof DocsGuiAnalyticsRoute
  '/_docs/gui/chat-composer': typeof DocsGuiChatComposerRoute
  '/_docs/gui/code-editor': typeof DocsGuiCodeEditorRoute
  '/_docs/gui/extensions': typeof DocsGuiExtensionsRoute
  '/_docs/gui/first-run': typeof DocsGuiFirstRunRoute
  '/_docs/gui/git-diff': typeof DocsGuiGitDiffRoute
  '/_docs/gui/import-graph': typeof DocsGuiImportGraphRoute
  '/_docs/gui/layout': typeof DocsGuiLayoutRoute
  '/_docs/gui/oauth': typeof DocsGuiOauthRoute
  '/_docs/gui/provider-model': typeof DocsGuiProviderModelRoute
  '/_docs/tui/commands-adddir': typeof DocsTuiCommandsAdddirRoute
  '/_docs/tui/commands-agents': typeof DocsTuiCommandsAgentsRoute
  '/_docs/tui/commands-all': typeof DocsTuiCommandsAllRoute
  '/_docs/tui/commands-attach': typeof DocsTuiCommandsAttachRoute
  '/_docs/tui/commands-bash': typeof DocsTuiCommandsBashRoute
  '/_docs/tui/commands-cd': typeof DocsTuiCommandsCdRoute
  '/_docs/tui/commands-clear': typeof DocsTuiCommandsClearRoute
  '/_docs/tui/commands-compact': typeof DocsTuiCommandsCompactRoute
  '/_docs/tui/commands-effort': typeof DocsTuiCommandsEffortRoute
  '/_docs/tui/commands-extension': typeof DocsTuiCommandsExtensionRoute
  '/_docs/tui/commands-free': typeof DocsTuiCommandsFreeRoute
  '/_docs/tui/commands-help': typeof DocsTuiCommandsHelpRoute
  '/_docs/tui/commands-internet': typeof DocsTuiCommandsInternetRoute
  '/_docs/tui/commands-mcp': typeof DocsTuiCommandsMcpRoute
  '/_docs/tui/commands-mode': typeof DocsTuiCommandsModeRoute
  '/_docs/tui/commands-model': typeof DocsTuiCommandsModelRoute
  '/_docs/tui/commands-new': typeof DocsTuiCommandsNewRoute
  '/_docs/tui/commands-quit': typeof DocsTuiCommandsQuitRoute
  '/_docs/tui/commands-remote': typeof DocsTuiCommandsRemoteRoute
  '/_docs/tui/commands-rename': typeof DocsTuiCommandsRenameRoute
  '/_docs/tui/commands-resume': typeof DocsTuiCommandsResumeRoute
  '/_docs/tui/commands-security': typeof DocsTuiCommandsSecurityRoute
  '/_docs/tui/commands-select': typeof DocsTuiCommandsSelectRoute
  '/_docs/tui/commands-skill': typeof DocsTuiCommandsSkillRoute
  '/_docs/tui/commands-store': typeof DocsTuiCommandsStoreRoute
  '/_docs/tui/commands-task': typeof DocsTuiCommandsTaskRoute
  '/_docs/tui/commands-todo': typeof DocsTuiCommandsTodoRoute
  '/_docs/tui/commands-usage': typeof DocsTuiCommandsUsageRoute
  '/_docs/tui/first-run': typeof DocsTuiFirstRunRoute
  '/_docs/tui/keyboard-shortcuts': typeof DocsTuiKeyboardShortcutsRoute
  '/_docs/tui/oauth': typeof DocsTuiOauthRoute
  '/_docs/tui/provider-model': typeof DocsTuiProviderModelRoute
  '/_docs/tui/settings-appearance': typeof DocsTuiSettingsAppearanceRoute
  '/_docs/tui/settings-general': typeof DocsTuiSettingsGeneralRoute
  '/_docs/tui/settings-model': typeof DocsTuiSettingsModelRoute
  '/_docs/tui/settings-oauth': typeof DocsTuiSettingsOauthRoute
  '/_docs/tui/settings-provider': typeof DocsTuiSettingsProviderRoute
  '/_docs/welcome/architecture': typeof DocsWelcomeArchitectureRoute
  '/_docs/welcome/getting-started': typeof DocsWelcomeGettingStartedRoute
  '/_docs/docs/': typeof DocsDocsIndexRoute
  '/_docs/gui/': typeof DocsGuiIndexRoute
  '/_docs/tui/': typeof DocsTuiIndexRoute
  '/_docs/welcome/': typeof DocsWelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/gui'
    | '/tui'
    | '/welcome'
    | '/docs/$slug'
    | '/gui/analytics'
    | '/gui/chat-composer'
    | '/gui/code-editor'
    | '/gui/extensions'
    | '/gui/first-run'
    | '/gui/git-diff'
    | '/gui/import-graph'
    | '/gui/layout'
    | '/gui/oauth'
    | '/gui/provider-model'
    | '/tui/commands-adddir'
    | '/tui/commands-agents'
    | '/tui/commands-all'
    | '/tui/commands-attach'
    | '/tui/commands-bash'
    | '/tui/commands-cd'
    | '/tui/commands-clear'
    | '/tui/commands-compact'
    | '/tui/commands-effort'
    | '/tui/commands-extension'
    | '/tui/commands-free'
    | '/tui/commands-help'
    | '/tui/commands-internet'
    | '/tui/commands-mcp'
    | '/tui/commands-mode'
    | '/tui/commands-model'
    | '/tui/commands-new'
    | '/tui/commands-quit'
    | '/tui/commands-remote'
    | '/tui/commands-rename'
    | '/tui/commands-resume'
    | '/tui/commands-security'
    | '/tui/commands-select'
    | '/tui/commands-skill'
    | '/tui/commands-store'
    | '/tui/commands-task'
    | '/tui/commands-todo'
    | '/tui/commands-usage'
    | '/tui/first-run'
    | '/tui/keyboard-shortcuts'
    | '/tui/oauth'
    | '/tui/provider-model'
    | '/tui/settings-appearance'
    | '/tui/settings-general'
    | '/tui/settings-model'
    | '/tui/settings-oauth'
    | '/tui/settings-provider'
    | '/welcome/architecture'
    | '/welcome/getting-started'
    | '/docs/'
    | '/gui/'
    | '/tui/'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$slug'
    | '/gui/analytics'
    | '/gui/chat-composer'
    | '/gui/code-editor'
    | '/gui/extensions'
    | '/gui/first-run'
    | '/gui/git-diff'
    | '/gui/import-graph'
    | '/gui/layout'
    | '/gui/oauth'
    | '/gui/provider-model'
    | '/tui/commands-adddir'
    | '/tui/commands-agents'
    | '/tui/commands-all'
    | '/tui/commands-attach'
    | '/tui/commands-bash'
    | '/tui/commands-cd'
    | '/tui/commands-clear'
    | '/tui/commands-compact'
    | '/tui/commands-effort'
    | '/tui/commands-extension'
    | '/tui/commands-free'
    | '/tui/commands-help'
    | '/tui/commands-internet'
    | '/tui/commands-mcp'
    | '/tui/commands-mode'
    | '/tui/commands-model'
    | '/tui/commands-new'
    | '/tui/commands-quit'
    | '/tui/commands-remote'
    | '/tui/commands-rename'
    | '/tui/commands-resume'
    | '/tui/commands-security'
    | '/tui/commands-select'
    | '/tui/commands-skill'
    | '/tui/commands-store'
    | '/tui/commands-task'
    | '/tui/commands-todo'
    | '/tui/commands-usage'
    | '/tui/first-run'
    | '/tui/keyboard-shortcuts'
    | '/tui/oauth'
    | '/tui/provider-model'
    | '/tui/settings-appearance'
    | '/tui/settings-general'
    | '/tui/settings-model'
    | '/tui/settings-oauth'
    | '/tui/settings-provider'
    | '/welcome/architecture'
    | '/welcome/getting-started'
    | '/docs'
    | '/gui'
    | '/tui'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/_docs'
    | '/_docs/docs'
    | '/_docs/gui'
    | '/_docs/tui'
    | '/_docs/welcome'
    | '/_docs/docs/$slug'
    | '/_docs/gui/analytics'
    | '/_docs/gui/chat-composer'
    | '/_docs/gui/code-editor'
    | '/_docs/gui/extensions'
    | '/_docs/gui/first-run'
    | '/_docs/gui/git-diff'
    | '/_docs/gui/import-graph'
    | '/_docs/gui/layout'
    | '/_docs/gui/oauth'
    | '/_docs/gui/provider-model'
    | '/_docs/tui/commands-adddir'
    | '/_docs/tui/commands-agents'
    | '/_docs/tui/commands-all'
    | '/_docs/tui/commands-attach'
    | '/_docs/tui/commands-bash'
    | '/_docs/tui/commands-cd'
    | '/_docs/tui/commands-clear'
    | '/_docs/tui/commands-compact'
    | '/_docs/tui/commands-effort'
    | '/_docs/tui/commands-extension'
    | '/_docs/tui/commands-free'
    | '/_docs/tui/commands-help'
    | '/_docs/tui/commands-internet'
    | '/_docs/tui/commands-mcp'
    | '/_docs/tui/commands-mode'
    | '/_docs/tui/commands-model'
    | '/_docs/tui/commands-new'
    | '/_docs/tui/commands-quit'
    | '/_docs/tui/commands-remote'
    | '/_docs/tui/commands-rename'
    | '/_docs/tui/commands-resume'
    | '/_docs/tui/commands-security'
    | '/_docs/tui/commands-select'
    | '/_docs/tui/commands-skill'
    | '/_docs/tui/commands-store'
    | '/_docs/tui/commands-task'
    | '/_docs/tui/commands-todo'
    | '/_docs/tui/commands-usage'
    | '/_docs/tui/first-run'
    | '/_docs/tui/keyboard-shortcuts'
    | '/_docs/tui/oauth'
    | '/_docs/tui/provider-model'
    | '/_docs/tui/settings-appearance'
    | '/_docs/tui/settings-general'
    | '/_docs/tui/settings-model'
    | '/_docs/tui/settings-oauth'
    | '/_docs/tui/settings-provider'
    | '/_docs/welcome/architecture'
    | '/_docs/welcome/getting-started'
    | '/_docs/docs/'
    | '/_docs/gui/'
    | '/_docs/tui/'
    | '/_docs/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs': {
      id: '/_docs/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsDocsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/gui': {
      id: '/_docs/gui'
      path: '/gui'
      fullPath: '/gui'
      preLoaderRoute: typeof DocsGuiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/tui': {
      id: '/_docs/tui'
      path: '/tui'
      fullPath: '/tui'
      preLoaderRoute: typeof DocsTuiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/welcome': {
      id: '/_docs/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof DocsWelcomeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_docs/docs/': {
      id: '/_docs/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsDocsIndexRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/docs/$slug': {
      id: '/_docs/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsDocsSlugRouteImport
      parentRoute: typeof DocsDocsRoute
    }
    '/_docs/gui/': {
      id: '/_docs/gui/'
      path: '/'
      fullPath: '/gui/'
      preLoaderRoute: typeof DocsGuiIndexRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/analytics': {
      id: '/_docs/gui/analytics'
      path: '/analytics'
      fullPath: '/gui/analytics'
      preLoaderRoute: typeof DocsGuiAnalyticsRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/chat-composer': {
      id: '/_docs/gui/chat-composer'
      path: '/chat-composer'
      fullPath: '/gui/chat-composer'
      preLoaderRoute: typeof DocsGuiChatComposerRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/code-editor': {
      id: '/_docs/gui/code-editor'
      path: '/code-editor'
      fullPath: '/gui/code-editor'
      preLoaderRoute: typeof DocsGuiCodeEditorRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/extensions': {
      id: '/_docs/gui/extensions'
      path: '/extensions'
      fullPath: '/gui/extensions'
      preLoaderRoute: typeof DocsGuiExtensionsRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/first-run': {
      id: '/_docs/gui/first-run'
      path: '/first-run'
      fullPath: '/gui/first-run'
      preLoaderRoute: typeof DocsGuiFirstRunRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/git-diff': {
      id: '/_docs/gui/git-diff'
      path: '/git-diff'
      fullPath: '/gui/git-diff'
      preLoaderRoute: typeof DocsGuiGitDiffRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/import-graph': {
      id: '/_docs/gui/import-graph'
      path: '/import-graph'
      fullPath: '/gui/import-graph'
      preLoaderRoute: typeof DocsGuiImportGraphRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/layout': {
      id: '/_docs/gui/layout'
      path: '/layout'
      fullPath: '/gui/layout'
      preLoaderRoute: typeof DocsGuiLayoutRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/oauth': {
      id: '/_docs/gui/oauth'
      path: '/oauth'
      fullPath: '/gui/oauth'
      preLoaderRoute: typeof DocsGuiOauthRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/gui/provider-model': {
      id: '/_docs/gui/provider-model'
      path: '/provider-model'
      fullPath: '/gui/provider-model'
      preLoaderRoute: typeof DocsGuiProviderModelRouteImport
      parentRoute: typeof DocsGuiRoute
    }
    '/_docs/tui/': {
      id: '/_docs/tui/'
      path: '/'
      fullPath: '/tui/'
      preLoaderRoute: typeof DocsTuiIndexRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-adddir': {
      id: '/_docs/tui/commands-adddir'
      path: '/commands-adddir'
      fullPath: '/tui/commands-adddir'
      preLoaderRoute: typeof DocsTuiCommandsAdddirRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-agents': {
      id: '/_docs/tui/commands-agents'
      path: '/commands-agents'
      fullPath: '/tui/commands-agents'
      preLoaderRoute: typeof DocsTuiCommandsAgentsRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-all': {
      id: '/_docs/tui/commands-all'
      path: '/commands-all'
      fullPath: '/tui/commands-all'
      preLoaderRoute: typeof DocsTuiCommandsAllRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-attach': {
      id: '/_docs/tui/commands-attach'
      path: '/commands-attach'
      fullPath: '/tui/commands-attach'
      preLoaderRoute: typeof DocsTuiCommandsAttachRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-bash': {
      id: '/_docs/tui/commands-bash'
      path: '/commands-bash'
      fullPath: '/tui/commands-bash'
      preLoaderRoute: typeof DocsTuiCommandsBashRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-cd': {
      id: '/_docs/tui/commands-cd'
      path: '/commands-cd'
      fullPath: '/tui/commands-cd'
      preLoaderRoute: typeof DocsTuiCommandsCdRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-clear': {
      id: '/_docs/tui/commands-clear'
      path: '/commands-clear'
      fullPath: '/tui/commands-clear'
      preLoaderRoute: typeof DocsTuiCommandsClearRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-compact': {
      id: '/_docs/tui/commands-compact'
      path: '/commands-compact'
      fullPath: '/tui/commands-compact'
      preLoaderRoute: typeof DocsTuiCommandsCompactRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-effort': {
      id: '/_docs/tui/commands-effort'
      path: '/commands-effort'
      fullPath: '/tui/commands-effort'
      preLoaderRoute: typeof DocsTuiCommandsEffortRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-extension': {
      id: '/_docs/tui/commands-extension'
      path: '/commands-extension'
      fullPath: '/tui/commands-extension'
      preLoaderRoute: typeof DocsTuiCommandsExtensionRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-free': {
      id: '/_docs/tui/commands-free'
      path: '/commands-free'
      fullPath: '/tui/commands-free'
      preLoaderRoute: typeof DocsTuiCommandsFreeRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-help': {
      id: '/_docs/tui/commands-help'
      path: '/commands-help'
      fullPath: '/tui/commands-help'
      preLoaderRoute: typeof DocsTuiCommandsHelpRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-internet': {
      id: '/_docs/tui/commands-internet'
      path: '/commands-internet'
      fullPath: '/tui/commands-internet'
      preLoaderRoute: typeof DocsTuiCommandsInternetRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-mcp': {
      id: '/_docs/tui/commands-mcp'
      path: '/commands-mcp'
      fullPath: '/tui/commands-mcp'
      preLoaderRoute: typeof DocsTuiCommandsMcpRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-mode': {
      id: '/_docs/tui/commands-mode'
      path: '/commands-mode'
      fullPath: '/tui/commands-mode'
      preLoaderRoute: typeof DocsTuiCommandsModeRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-model': {
      id: '/_docs/tui/commands-model'
      path: '/commands-model'
      fullPath: '/tui/commands-model'
      preLoaderRoute: typeof DocsTuiCommandsModelRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-new': {
      id: '/_docs/tui/commands-new'
      path: '/commands-new'
      fullPath: '/tui/commands-new'
      preLoaderRoute: typeof DocsTuiCommandsNewRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-quit': {
      id: '/_docs/tui/commands-quit'
      path: '/commands-quit'
      fullPath: '/tui/commands-quit'
      preLoaderRoute: typeof DocsTuiCommandsQuitRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-remote': {
      id: '/_docs/tui/commands-remote'
      path: '/commands-remote'
      fullPath: '/tui/commands-remote'
      preLoaderRoute: typeof DocsTuiCommandsRemoteRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-rename': {
      id: '/_docs/tui/commands-rename'
      path: '/commands-rename'
      fullPath: '/tui/commands-rename'
      preLoaderRoute: typeof DocsTuiCommandsRenameRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-resume': {
      id: '/_docs/tui/commands-resume'
      path: '/commands-resume'
      fullPath: '/tui/commands-resume'
      preLoaderRoute: typeof DocsTuiCommandsResumeRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-security': {
      id: '/_docs/tui/commands-security'
      path: '/commands-security'
      fullPath: '/tui/commands-security'
      preLoaderRoute: typeof DocsTuiCommandsSecurityRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-select': {
      id: '/_docs/tui/commands-select'
      path: '/commands-select'
      fullPath: '/tui/commands-select'
      preLoaderRoute: typeof DocsTuiCommandsSelectRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-skill': {
      id: '/_docs/tui/commands-skill'
      path: '/commands-skill'
      fullPath: '/tui/commands-skill'
      preLoaderRoute: typeof DocsTuiCommandsSkillRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-store': {
      id: '/_docs/tui/commands-store'
      path: '/commands-store'
      fullPath: '/tui/commands-store'
      preLoaderRoute: typeof DocsTuiCommandsStoreRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-task': {
      id: '/_docs/tui/commands-task'
      path: '/commands-task'
      fullPath: '/tui/commands-task'
      preLoaderRoute: typeof DocsTuiCommandsTaskRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-todo': {
      id: '/_docs/tui/commands-todo'
      path: '/commands-todo'
      fullPath: '/tui/commands-todo'
      preLoaderRoute: typeof DocsTuiCommandsTodoRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/commands-usage': {
      id: '/_docs/tui/commands-usage'
      path: '/commands-usage'
      fullPath: '/tui/commands-usage'
      preLoaderRoute: typeof DocsTuiCommandsUsageRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/first-run': {
      id: '/_docs/tui/first-run'
      path: '/first-run'
      fullPath: '/tui/first-run'
      preLoaderRoute: typeof DocsTuiFirstRunRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/keyboard-shortcuts': {
      id: '/_docs/tui/keyboard-shortcuts'
      path: '/keyboard-shortcuts'
      fullPath: '/tui/keyboard-shortcuts'
      preLoaderRoute: typeof DocsTuiKeyboardShortcutsRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/oauth': {
      id: '/_docs/tui/oauth'
      path: '/oauth'
      fullPath: '/tui/oauth'
      preLoaderRoute: typeof DocsTuiOauthRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/provider-model': {
      id: '/_docs/tui/provider-model'
      path: '/provider-model'
      fullPath: '/tui/provider-model'
      preLoaderRoute: typeof DocsTuiProviderModelRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/settings-appearance': {
      id: '/_docs/tui/settings-appearance'
      path: '/settings-appearance'
      fullPath: '/tui/settings-appearance'
      preLoaderRoute: typeof DocsTuiSettingsAppearanceRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/settings-general': {
      id: '/_docs/tui/settings-general'
      path: '/settings-general'
      fullPath: '/tui/settings-general'
      preLoaderRoute: typeof DocsTuiSettingsGeneralRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/settings-model': {
      id: '/_docs/tui/settings-model'
      path: '/settings-model'
      fullPath: '/tui/settings-model'
      preLoaderRoute: typeof DocsTuiSettingsModelRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/settings-oauth': {
      id: '/_docs/tui/settings-oauth'
      path: '/settings-oauth'
      fullPath: '/tui/settings-oauth'
      preLoaderRoute: typeof DocsTuiSettingsOauthRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/tui/settings-provider': {
      id: '/_docs/tui/settings-provider'
      path: '/settings-provider'
      fullPath: '/tui/settings-provider'
      preLoaderRoute: typeof DocsTuiSettingsProviderRouteImport
      parentRoute: typeof DocsTuiRoute
    }
    '/_docs/welcome/': {
      id: '/_docs/welcome/'
      path: '/'
      fullPath: '/welcome/'
      preLoaderRoute: typeof DocsWelcomeIndexRouteImport
      parentRoute: typeof DocsWelcomeRoute
    }
    '/_docs/welcome/architecture': {
      id: '/_docs/welcome/architecture'
      path: '/architecture'
      fullPath: '/welcome/architecture'
      preLoaderRoute: typeof DocsWelcomeArchitectureRouteImport
      parentRoute: typeof DocsWelcomeRoute
    }
    '/_docs/welcome/getting-started': {
      id: '/_docs/welcome/getting-started'
      path: '/getting-started'
      fullPath: '/welcome/getting-started'
      preLoaderRoute: typeof DocsWelcomeGettingStartedRouteImport
      parentRoute: typeof DocsWelcomeRoute
    }
  }
}

interface DocsDocsRouteChildren {
  DocsDocsSlugRoute: typeof DocsDocsSlugRoute
  DocsDocsIndexRoute: typeof DocsDocsIndexRoute
}

const DocsDocsRouteChildren: DocsDocsRouteChildren = {
  DocsDocsSlugRoute: DocsDocsSlugRoute,
  DocsDocsIndexRoute: DocsDocsIndexRoute,
}

const DocsDocsRouteWithChildren = DocsDocsRoute._addFileChildren(
  DocsDocsRouteChildren,
)

interface DocsGuiRouteChildren {
  DocsGuiAnalyticsRoute: typeof DocsGuiAnalyticsRoute
  DocsGuiChatComposerRoute: typeof DocsGuiChatComposerRoute
  DocsGuiCodeEditorRoute: typeof DocsGuiCodeEditorRoute
  DocsGuiExtensionsRoute: typeof DocsGuiExtensionsRoute
  DocsGuiFirstRunRoute: typeof DocsGuiFirstRunRoute
  DocsGuiGitDiffRoute: typeof DocsGuiGitDiffRoute
  DocsGuiImportGraphRoute: typeof DocsGuiImportGraphRoute
  DocsGuiLayoutRoute: typeof DocsGuiLayoutRoute
  DocsGuiOauthRoute: typeof DocsGuiOauthRoute
  DocsGuiProviderModelRoute: typeof DocsGuiProviderModelRoute
  DocsGuiIndexRoute: typeof DocsGuiIndexRoute
}

const DocsGuiRouteChildren: DocsGuiRouteChildren = {
  DocsGuiAnalyticsRoute: DocsGuiAnalyticsRoute,
  DocsGuiChatComposerRoute: DocsGuiChatComposerRoute,
  DocsGuiCodeEditorRoute: DocsGuiCodeEditorRoute,
  DocsGuiExtensionsRoute: DocsGuiExtensionsRoute,
  DocsGuiFirstRunRoute: DocsGuiFirstRunRoute,
  DocsGuiGitDiffRoute: DocsGuiGitDiffRoute,
  DocsGuiImportGraphRoute: DocsGuiImportGraphRoute,
  DocsGuiLayoutRoute: DocsGuiLayoutRoute,
  DocsGuiOauthRoute: DocsGuiOauthRoute,
  DocsGuiProviderModelRoute: DocsGuiProviderModelRoute,
  DocsGuiIndexRoute: DocsGuiIndexRoute,
}

const DocsGuiRouteWithChildren =
  DocsGuiRoute._addFileChildren(DocsGuiRouteChildren)

interface DocsTuiRouteChildren {
  DocsTuiCommandsAdddirRoute: typeof DocsTuiCommandsAdddirRoute
  DocsTuiCommandsAgentsRoute: typeof DocsTuiCommandsAgentsRoute
  DocsTuiCommandsAllRoute: typeof DocsTuiCommandsAllRoute
  DocsTuiCommandsAttachRoute: typeof DocsTuiCommandsAttachRoute
  DocsTuiCommandsBashRoute: typeof DocsTuiCommandsBashRoute
  DocsTuiCommandsCdRoute: typeof DocsTuiCommandsCdRoute
  DocsTuiCommandsClearRoute: typeof DocsTuiCommandsClearRoute
  DocsTuiCommandsCompactRoute: typeof DocsTuiCommandsCompactRoute
  DocsTuiCommandsEffortRoute: typeof DocsTuiCommandsEffortRoute
  DocsTuiCommandsExtensionRoute: typeof DocsTuiCommandsExtensionRoute
  DocsTuiCommandsFreeRoute: typeof DocsTuiCommandsFreeRoute
  DocsTuiCommandsHelpRoute: typeof DocsTuiCommandsHelpRoute
  DocsTuiCommandsInternetRoute: typeof DocsTuiCommandsInternetRoute
  DocsTuiCommandsMcpRoute: typeof DocsTuiCommandsMcpRoute
  DocsTuiCommandsModeRoute: typeof DocsTuiCommandsModeRoute
  DocsTuiCommandsModelRoute: typeof DocsTuiCommandsModelRoute
  DocsTuiCommandsNewRoute: typeof DocsTuiCommandsNewRoute
  DocsTuiCommandsQuitRoute: typeof DocsTuiCommandsQuitRoute
  DocsTuiCommandsRemoteRoute: typeof DocsTuiCommandsRemoteRoute
  DocsTuiCommandsRenameRoute: typeof DocsTuiCommandsRenameRoute
  DocsTuiCommandsResumeRoute: typeof DocsTuiCommandsResumeRoute
  DocsTuiCommandsSecurityRoute: typeof DocsTuiCommandsSecurityRoute
  DocsTuiCommandsSelectRoute: typeof DocsTuiCommandsSelectRoute
  DocsTuiCommandsSkillRoute: typeof DocsTuiCommandsSkillRoute
  DocsTuiCommandsStoreRoute: typeof DocsTuiCommandsStoreRoute
  DocsTuiCommandsTaskRoute: typeof DocsTuiCommandsTaskRoute
  DocsTuiCommandsTodoRoute: typeof DocsTuiCommandsTodoRoute
  DocsTuiCommandsUsageRoute: typeof DocsTuiCommandsUsageRoute
  DocsTuiFirstRunRoute: typeof DocsTuiFirstRunRoute
  DocsTuiKeyboardShortcutsRoute: typeof DocsTuiKeyboardShortcutsRoute
  DocsTuiOauthRoute: typeof DocsTuiOauthRoute
  DocsTuiProviderModelRoute: typeof DocsTuiProviderModelRoute
  DocsTuiSettingsAppearanceRoute: typeof DocsTuiSettingsAppearanceRoute
  DocsTuiSettingsGeneralRoute: typeof DocsTuiSettingsGeneralRoute
  DocsTuiSettingsModelRoute: typeof DocsTuiSettingsModelRoute
  DocsTuiSettingsOauthRoute: typeof DocsTuiSettingsOauthRoute
  DocsTuiSettingsProviderRoute: typeof DocsTuiSettingsProviderRoute
  DocsTuiIndexRoute: typeof DocsTuiIndexRoute
}

const DocsTuiRouteChildren: DocsTuiRouteChildren = {
  DocsTuiCommandsAdddirRoute: DocsTuiCommandsAdddirRoute,
  DocsTuiCommandsAgentsRoute: DocsTuiCommandsAgentsRoute,
  DocsTuiCommandsAllRoute: DocsTuiCommandsAllRoute,
  DocsTuiCommandsAttachRoute: DocsTuiCommandsAttachRoute,
  DocsTuiCommandsBashRoute: DocsTuiCommandsBashRoute,
  DocsTuiCommandsCdRoute: DocsTuiCommandsCdRoute,
  DocsTuiCommandsClearRoute: DocsTuiCommandsClearRoute,
  DocsTuiCommandsCompactRoute: DocsTuiCommandsCompactRoute,
  DocsTuiCommandsEffortRoute: DocsTuiCommandsEffortRoute,
  DocsTuiCommandsExtensionRoute: DocsTuiCommandsExtensionRoute,
  DocsTuiCommandsFreeRoute: DocsTuiCommandsFreeRoute,
  DocsTuiCommandsHelpRoute: DocsTuiCommandsHelpRoute,
  DocsTuiCommandsInternetRoute: DocsTuiCommandsInternetRoute,
  DocsTuiCommandsMcpRoute: DocsTuiCommandsMcpRoute,
  DocsTuiCommandsModeRoute: DocsTuiCommandsModeRoute,
  DocsTuiCommandsModelRoute: DocsTuiCommandsModelRoute,
  DocsTuiCommandsNewRoute: DocsTuiCommandsNewRoute,
  DocsTuiCommandsQuitRoute: DocsTuiCommandsQuitRoute,
  DocsTuiCommandsRemoteRoute: DocsTuiCommandsRemoteRoute,
  DocsTuiCommandsRenameRoute: DocsTuiCommandsRenameRoute,
  DocsTuiCommandsResumeRoute: DocsTuiCommandsResumeRoute,
  DocsTuiCommandsSecurityRoute: DocsTuiCommandsSecurityRoute,
  DocsTuiCommandsSelectRoute: DocsTuiCommandsSelectRoute,
  DocsTuiCommandsSkillRoute: DocsTuiCommandsSkillRoute,
  DocsTuiCommandsStoreRoute: DocsTuiCommandsStoreRoute,
  DocsTuiCommandsTaskRoute: DocsTuiCommandsTaskRoute,
  DocsTuiCommandsTodoRoute: DocsTuiCommandsTodoRoute,
  DocsTuiCommandsUsageRoute: DocsTuiCommandsUsageRoute,
  DocsTuiFirstRunRoute: DocsTuiFirstRunRoute,
  DocsTuiKeyboardShortcutsRoute: DocsTuiKeyboardShortcutsRoute,
  DocsTuiOauthRoute: DocsTuiOauthRoute,
  DocsTuiProviderModelRoute: DocsTuiProviderModelRoute,
  DocsTuiSettingsAppearanceRoute: DocsTuiSettingsAppearanceRoute,
  DocsTuiSettingsGeneralRoute: DocsTuiSettingsGeneralRoute,
  DocsTuiSettingsModelRoute: DocsTuiSettingsModelRoute,
  DocsTuiSettingsOauthRoute: DocsTuiSettingsOauthRoute,
  DocsTuiSettingsProviderRoute: DocsTuiSettingsProviderRoute,
  DocsTuiIndexRoute: DocsTuiIndexRoute,
}

const DocsTuiRouteWithChildren =
  DocsTuiRoute._addFileChildren(DocsTuiRouteChildren)

interface DocsWelcomeRouteChildren {
  DocsWelcomeArchitectureRoute: typeof DocsWelcomeArchitectureRoute
  DocsWelcomeGettingStartedRoute: typeof DocsWelcomeGettingStartedRoute
  DocsWelcomeIndexRoute: typeof DocsWelcomeIndexRoute
}

const DocsWelcomeRouteChildren: DocsWelcomeRouteChildren = {
  DocsWelcomeArchitectureRoute: DocsWelcomeArchitectureRoute,
  DocsWelcomeGettingStartedRoute: DocsWelcomeGettingStartedRoute,
  DocsWelcomeIndexRoute: DocsWelcomeIndexRoute,
}

const DocsWelcomeRouteWithChildren = DocsWelcomeRoute._addFileChildren(
  DocsWelcomeRouteChildren,
)

interface DocsRouteChildren {
  DocsDocsRoute: typeof DocsDocsRouteWithChildren
  DocsGuiRoute: typeof DocsGuiRouteWithChildren
  DocsTuiRoute: typeof DocsTuiRouteWithChildren
  DocsWelcomeRoute: typeof DocsWelcomeRouteWithChildren
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsRoute: DocsDocsRouteWithChildren,
  DocsGuiRoute: DocsGuiRouteWithChildren,
  DocsTuiRoute: DocsTuiRouteWithChildren,
  DocsWelcomeRoute: DocsWelcomeRouteWithChildren,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
